### ISSUE TITLE
add libcurl4-openssl-dev and libmysqlclient-dev to ruby template

### ISSUE THREAD

**Issue by onceatime** [hashicorp/otto#104]
to build some native gems like mysql2 its required to have the headers on vagrant machine. If possible please add:

libcurl4-openssl-dev
libmysqlclient-dev

or better add a configuration point in Appfile for dynamic dependencies.

**Comment by onceatime** [comment]
i forgot imagemagick

**Comment by justincampbell** [comment]
These should now be detected and installed. Thanks!
