### ISSUE TITLE
"git: command not found" in setup for type="go"

### ISSUE THREAD

**Issue by sivy** [hashicorp/otto#109]
With a basic AppFile:

    application {
      name = "test_service"
      type = "go"
    }

`otto dev` hit this:

	==> default: Mounting shared folders...
	    default: /otto/foundation-1 => /Users/sivy/projects/gocode/src/github.com/sivy/test_service/.otto/compiled/app/foundation-consul/app-dev
	    default: /opt/gopath/src/github.com/sivy/test_service => /Users/sivy/projects/gocode/src/github.com/sivy/test_service
	==> default: Running provisioner: shell...
	    default: Running: inline script
	==> default: stdin: is not a tty
	==> default: [otto] Installing Consul...
	==> default: [otto] Installing dnsmasq for Consul...
	==> default: [otto] Configuring consul service: test_service
	==> default: Running provisioner: shell...
	    default: Running: inline script
	==> default: stdin: is not a tty
	==> default: [otto] Downloading Go 1.5...
	==> default: [otto] Untarring Go...
	==> default: [otto] Making GOPATH...
	==> default: [otto] Setting up PATH...
	==> default: [otto] Installing VCSs for go get...
	==> default: [otto] Configuring Go to use SSH instead of HTTP...
	==> default: /tmp/vagrant-shell: line 32: git: command not found
	The SSH command responded with a non-zero exit status. Vagrant
	assumes that this means the command failed. The output for this command
	should be in the log above. Please read the output to determine what
	went wrong.

	Error building dev environment: Error executing Vagrant: exit status 1

**Comment by chiefy** [comment]
:+1: Different scenario, but I just ran into this as well when trying to `npm install` w/ git repos in `package.json`. Is there any way to add provisioning, or specify packages to install in the `Appfile?`

**Comment by sivy** [comment]
Also, after this point I `otto dev ssh` but am NOT put into the working directory of the code under development.

**Comment by sethvargo** [comment]
@sivy @chiefy do you have go installed? Go needs git, mercurial, and a few other dependencies in order to download it's dependencies. This is definitely a bug, but I'm trying to figure out if this is a $PATH bug or a missing dep bug.

**Comment by sivy** [comment]
Go installed where? It's installed and working on my local Mac laptop.

**Comment by sethvargo** [comment]
@sivy sorry - I meant "git", not "go"

**Comment by sivy** [comment]
Yes, I also have git installed on the Mac. Full working Go dev environment, `$GOPATH` set, etc. Can `go install` and run the binary.

**Comment by sethvargo** [comment]
Okay cool - so this looks more like a $PATH issue than a tools issue :smile: - just helps us in digging deeper.

**Comment by chiefy** [comment]
@sethvargo sorry, my situation is a little different, my node-based project needs git, want me to open a new ticket?

**Comment by sivy** [comment]
So @sethvargo where is otto getting the tools that it uses in the vagrant environment? I thought they would come along with the vagrant image that otto downloads.

**Comment by danawoodman** [comment]
Same issue as @chiefy, I'm getting command not found on a node.js project. Seems like git is being skipped for some reason:

```
==> default: [otto] Downloading Node 4.1.0...
==> default: [otto] Untarring Node...
==> default: [otto] Setting up PATH...
==> default: [otto] Installing build-essential for native packages...
==> default: [otto] Installing GCC/G++ 4.8 (required for newer Node versions)...
```

**Comment by sivy** [comment]
Just tried this again after running `otto dev destroy` and got the same error. Here's a (sanitized) log:

    C02Q3FUQG8WP:test_service sivy$ otto dev
    ==> Creating local development environment with Vagrant if it doesn't exist...
        Raw Vagrant output will begin streaming in below. Otto does
        not create this output. It is mirrored directly from Vagrant
        while the development environment is being created.
        
    Bringing machine 'default' up with 'virtualbox' provider...
    ==> default: Importing base box 'hashicorp/precise64'...
    ==> default: Matching MAC address for NAT networking...
    ==> default: Checking if box 'hashicorp/precise64' is up to date...
    ==> default: Setting the name of the VM: dev_default_1443755462819_69312
    ==> default: Clearing any previously set network interfaces...
    ==> default: Preparing network interfaces based on configuration...
        default: Adapter 1: nat
    ==> default: Forwarding ports...
        default: 22 => 2222 (adapter 1)
    ==> default: Booting VM...
    ==> default: Waiting for machine to boot. This may take a few minutes...
        default: SSH address: 127.0.0.1:2222
        default: SSH username: vagrant
        default: SSH auth method: private key
        default: 
        default: Vagrant insecure key detected. Vagrant will automatically replace
        default: this with a newly generated keypair for better security.
        default: 
        default: Inserting generated public key within guest...
        default: Removing insecure key from the guest if it's present...
        default: Key inserted! Disconnecting and reconnecting using new SSH key...
    ==> default: Machine booted and ready!
    ==> default: Checking for guest additions in VM...
        default: The guest additions on this VM do not match the installed version of
        default: VirtualBox! In most cases this is fine, but in rare cases it can
        default: prevent things such as shared folders from working properly. If you see
        default: shared folder errors, please make sure the guest additions within the
        default: virtual machine match the version of VirtualBox you have installed on
        default: your host and reload your VM.
        default: 
        default: Guest Additions Version: 4.2.0
        default: VirtualBox Version: 5.0
    ==> default: Mounting shared folders...
        default: /otto/foundation-1 => /Users/sivy/projects/gocode/src/github.com/sivy/test_service/.otto/compiled/app/foundation-consul/app-dev
        default: /opt/gopath/src/github.com/sivy/test_service => /Users/sivy/projects/gocode/src/github.com/sivy/test_service
    ==> default: Running provisioner: shell...
        default: Running: inline script
    ==> default: stdin: is not a tty
    ==> default: [otto] Installing Consul...
    ==> default: [otto] Installing dnsmasq for Consul...
    ==> default: [otto] Configuring consul service: test_service
    ==> default: Running provisioner: shell...
        default: Running: inline script
    ==> default: stdin: is not a tty
    ==> default: [otto] Downloading Go 1.5...
    ==> default: [otto] Untarring Go...
    ==> default: [otto] Making GOPATH...
    ==> default: [otto] Setting up PATH...
    ==> default: [otto] Installing VCSs for go get...
    ==> default: [otto] Configuring Go to use SSH instead of HTTP...
    ==> default: /tmp/vagrant-shell: line 32: git: command not found
    The SSH command responded with a non-zero exit status. Vagrant
    assumes that this means the command failed. The output for this command
    should be in the log above. Please read the output to determine what
    went wrong.

    Error building dev environment: Error executing Vagrant: exit status 1

    The error messages from Vagrant are usually very informative.
    Please read it carefully and fix any issues it mentions. If
    the message isn't clear, please report this to the Otto project.
    C02Q3FUQG8WP:test_service sivy$

**Comment by mitchellh** [comment]
This is super weird and I can't reproduce it, can you look in your `/var/log/syslog` and see if there are any error messages?

**Comment by sivy** [comment]
Hi @mitchellh, I'm on OS X, I don't have a `/var/log/syslog` (`/var/log/system.log` doesn't have anything either). Anywhere else to look?

**Comment by mitchellh** [comment]
Very sorry, I meant in the dev environment :)

**Comment by sivy** [comment]
(facepalm)

**Comment by sivy** [comment]
Ah, ok, looks like it might be a firewall/proxy issue (on work network). Not going to try and scrub all the output, but lots of:

    Oct  2 03:11:20 precise64 otto: Err http://us.archive.ubuntu.com/ubuntu/ precise/main git amd64   
    1:1.7.9.5-1
    Oct  2 03:11:20 precise64 otto:   Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.15 
    80]
    Oct  2 03:11:20 precise64 otto: Err http://us.archive.ubuntu.com/ubuntu/ precise/main libjs-jquery all 1   
    1.7.1-1ubuntu1
    Oct  2 03:11:20 precise64 otto:   Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.15 
    80]
    Oct  2 03:11:20 precise64 otto: Err http://us.archive.ubuntu.com/ubuntu/ precise/universe mercurial-
    common all 2.0.2-1ubuntu1
    Oct  2 03:11:20 precise64 otto:   Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.15 
    80]
    Oct  2 03:11:20 precise64 otto: Err http://us.archive.ubuntu.com/ubuntu/ precise/universe mercurial 
    amd64 2.0.2-1ubuntu1
    Oct  2 03:11:20 precise64 otto:   Unable to connect to us.archive.ubuntu.com:http: [IP: 91.189.91.15 
    80]

I'm tweaking my proxy settings and will see if that fixes anything. Surprised though that these did not surface during the vagrant run.

**Comment by sivy** [comment]
Ok, I haven't resolved it locally, but closing this out as it appears to be an issue with my local network/proxy, not otto.

Would request the issues with installing dependencies get surfaced in the vagrant output though.
