### ISSUE TITLE
Need control over IP range used for host-only networking

### ISSUE THREAD

**Issue by a7rk6s** [hashicorp/otto#113]
It appears that Otto will look for an address range that isn't used on any local interface, but this doesn't mean the range is available. In my case, it chose 172.16.1.*, which was already in use elsewhere.

There should be a way to globally specify a set of known available ranges that Otto can use.

In addition, it might be better if Otto didn't start from the "top" or the "bottom" of the IP ranges when searching. So when checking 172.16.0.0/16 for example, don't start at 172.16.0.0/24, start at (let's say) 172.25.91.0/24. Then the need for manual configuration might be reduced.

**Comment by mitchellh** [comment]
Ah darn! 

There isn't a way to do this right now, but this problem will just disappear in Otto 0.2 since we plan on switching to IPv6. I'll keep this open for now and close this when we do that.
