### ISSUE TITLE
Access to all terraform providers

### ISSUE THREAD

**Issue by cohix** [hashicorp/otto#115]
I'm sure this is incoming, but support for additional providers, i.e. Digital Ocean, would be very useful.

**Comment by rylanhalteman** [comment]
Yes please!

**Comment by mitchellh** [comment]
Yes, definitely coming. We architected Otto to easily support this. DO and GCE are coming.

**Comment by JesusLeon** [comment]
Looking forward!

**Comment by weaksauce** [comment]
is there a timeline for this for DO? what's involved with making this happen?

**Comment by betoharres** [comment]
+1

**Comment by josephholsten** [comment]
@mitchellh are there any tickets we can work on to get a non-aws infra out?

**Comment by roikles** [comment]
+1

**Comment by rollick** [comment]
Is there an update on this? I would be keen to help with Gandi as a provider.

**Comment by mitchellh** [comment]
We'll be taking a strong look at this for 0.3 but it'll likely be 0.4 or later. 0.3 will be the first version of Otto to dedicate making deployments production ready. As part of that, we'll likely stick to one or two providers but once we prove it we can grow it out greatly.

**Comment by niallobrien** [comment]
+1 for Digital Ocean support.
