### ISSUE TITLE
Help debugging

### ISSUE THREAD

**Issue by veggiemonk** [hashicorp/otto#117]
It would really be nice to have some pointers to how to debug otto. So sorry for this basic question, my knowledge of the Go ecosystem is not much but it would really save a lot of time. 

Are you using [godebug](https://github.com/mailgun/godebug) from mailgun?
Or this [in-browser debugger](https://github.com/simon-whitehead/go-debug)?

Or maybe share a bit of **your workflow**? :smile: That would be really interesting.

I have an error while starting a ssh connection, I noticed that the image is using the guest additions of VirtualBox 4.3.
```
> otto dev ssh
==> Executing SSH. This may take a few seconds...
exit status 255

> otto version
Otto v0.1.1

> VBoxManager --version
5.0.4r102546
```
On Ubuntu 14.04.3

Any idea on what that may be ?

Thank you for your help

**Comment by bascht** [comment]
You might not even need an elaborate Go debugging tool chain. The exit status 255 comes directly from the from ssh client and if it takes a few seconds for the error to pop up you could be running into firewall issues or something like that.

You can debug the actual connection `otto dev ssh` uses, with:

```
$ otto dev vagrant ssh-config
==> Executing: 'vagrant ssh-config'
Host default
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile […]/.otto/data/vagrant/machines/default/virtualbox/private_key
  IdentitiesOnly yes
  LogLevel FATAL
  ForwardAgent yes

$ nc -vw3 127.0.0.1 2222
Ncat: Version 6.47 ( http://nmap.org/ncat )
Ncat: Connected to 127.0.0.1:2222.
SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1
```

**Comment by veggiemonk** [comment]
Thank you so much. It was a problem with virtualbox kernel module.

**Comment by bascht** [comment]
Happy to help :)

**Comment by gustavoandrescabral** [comment]
@veggiemonk Can you tell me how did you fix it? Please, I'm having the same problem

**Comment by veggiemonk** [comment]
@gustavoandrescabral The problem is coming from the kernel module for VirtualBox.
The vm was not loaded so otto could not ssh into it.
Check your VirtualBox install, make sure the vm is running then retry.
It should solve your problem, i hope.
Let me know how it goes...

**Comment by gustavoandrescabral** [comment]
@veggiemonk I did it! I've reinstalled VBox, but with this packages
```sudo apt-get install linux-generic linux-image-generic linux-headers-generic linux-signed-generic```
Everything went alright

**Comment by veggiemonk** [comment]
Cool. Glad it is solved!
Yes, on Linux, VirtualBox needs those kernel headers to compile the kernel modules.

**Comment by veggiemonk** [comment]
Anyone? Where should we had that to the doc?
