### ISSUE TITLE
Python application support

### ISSUE THREAD

**Issue by mwarkentin** [hashicorp/otto#123]
I haven't had a chance to dig into the code yet to figure out what's required for a new type of language support, but maybe we can start collecting some of our Python best practices here for implementation.

Us Django/Flask/etc. devs need some Otto :heart: 

### Customizations
* Python 2/3
    * Which by default? 3.5?

### Installed bits

* [pip](https://pip.readthedocs.org/en/stable/)
* [virtualenv](https://virtualenv.pypa.io/en/latest/)
* [virtualenvwrapper](https://virtualenvwrapper.readthedocs.org/en/latest/)

**Comment by dkador** [comment]
:+1: to that request. :)

**Comment by jmetzmeier** [comment]
I am currently working on this. I have dev working but still need to test the build and deploy for AWS.

**Comment by mwarkentin** [comment]
@jmetzmeier Nice! Looking forward to the PR. :smile:

**Comment by jmetzmeier** [comment]
This branch has working Python support: https://github.com/jmetzmeier/otto/tree/python-support

It needs testing with more frameworks, as well as documentation updates.

**Comment by mwarkentin** [comment]
@jmetzmeier Nice! Which frameworks have you tested?

**Comment by jmetzmeier** [comment]
I have only tested Flask so far.

**Comment by justincampbell** [comment]
@jmetzmeier Thanks! Feel free to open a PR and say that it's still in progress to start the feedback process.

**Comment by justincampbell** [comment]
PR in #147
