### ISSUE TITLE
Not intuitive how to provision extra packages

### ISSUE THREAD

**Issue by chiefy** [hashicorp/otto#126]
see-also: #109 

My `node` based project depends on `git+https` and fails on `npm install` on dev guest environment.

**Comment by Teku** [comment]
Depending on your issue this may help as a _temporary_ solution:

```
sudo apt-get update
sudo apt-get install -y python-software-properties python g++ make
sudo add-apt-repository ppa:chris-lea/node.js
sudo apt-get update
sudo apt-get install nodejs
```

This solved my issues with `npm install`

**Comment by chiefy** [comment]
@Teku thanks, yeah I can `otto ssh` and `sudo apt-get install git` but it'd be nice if there was a way to use the `Appfile` to tell otto about any package dependencies your application has, and it would just automagically get installed w/ Vagrant provisioning.

**Comment by chiefy** [comment]
#133

**Comment by justincampbell** [comment]
@chiefy Ideally, common dev dependencies such as git would be available in dev environment automatically. Can open a PR adding that apt dependency?

**Comment by mitchellh** [comment]
This is now solved for node. For a more generic solution, we're still trying to think through a solution.
