### ISSUE TITLE
Support Ruby apps with package.json

### ISSUE THREAD

**Issue by faun** [hashicorp/otto#128]
Ruby apps that also have a package.json at the project root are incorrectly assumed to be a node project.

**Comment by faun** [comment]
See #124.

**Comment by justincampbell** [comment]
Fixed, thanks!

**Comment by faun** [comment]
That was fast, thanks!

**Comment by mdb** [comment]
@justincampbell Thanks for this! Is there a way for users to learn if/when your fix is present in an official release? I ask because I am experiencing this with a fresh `v0.1.1` installation downloaded from [ottoproject.io](https://ottoproject.io/downloads.html).

Thanks again!

**Comment by justincampbell** [comment]
@mdb CHANGELOG.md should be up to date

**Comment by justincampbell** [comment]
@mdb But somehow it wasn't :stuck_out_tongue: just added!

**Comment by faun** [comment]
@mdb Just to be clear: this has been fixed in 0.1.2 which is, as of yet, unreleased.

**Comment by mdb** [comment]
Thanks for the clarification @faun and @justincampbell. I see the bug fix is now cited in the 0.1.2 `CHANGELOG.md` release notes -- that's exactly what I was looking for previously.
