### ISSUE TITLE
Package dependency customizations

### ISSUE THREAD

**Issue by fromonesrc** [hashicorp/otto#133]
How would I add package dependencies specific to an app that wouldn't belong in the common ruby Vagrantfile? I thought Appfile would be the place to do this but doesn't currently look supported. #132 and #104 seem to be attempts at patching by having dependencies in common Vagrantfile.

**Comment by justincampbell** [comment]
@fromonesrc We now detect gems and install apt dependencies. Feel free to add to the list here: https://github.com/hashicorp/otto/blob/master/builtin/app/ruby/data/common/dev/Vagrantfile.tpl#L118-L124
