### ISSUE TITLE
apptype NodeJS : node/npm not installed

### ISSUE THREAD

**Issue by dublx** [hashicorp/otto#140]
Hi,
I was following the Getting Started tutorial and used a folder with a NodeJS app (folder has a package.json file but no appfile yet). Once I ssh'ed into the box I could see the node symlinks but they point to a inexisting file.

Let me know if further logs/output is needed.

**Comment by chiefy** [comment]
@dublx are you using otto 0.1.1? What's your `.otto/compiled/dev/Vagrantfile` look like?

**Comment by mitchellh** [comment]
Fixed
