### ISSUE TITLE
Application dependencies with customisation

### ISSUE THREAD

**Issue by davidwinter** [hashicorp/otto#141]
I've created a sample `mysql` dependency in my project with the following `Appfile`:

```
application {
    name = "mysql"
    type = "docker-external"
}

customization "mysql" {
    image = "mysql"
    run_args = "-e MYSQL_ROOT_PASSWORD=my-secret-pw -e MYSQL_DATABASE=localdev -p 3306:3306"
}
```

My project Appfile then references it using:

```
application {
  name = "ottotest"
  type = "ruby"

  dependency { source = "mysql" }
}
```

Is it possible when declaring this dependency in the above `Appfile` to override the `run_args` parameter so that different applications can use different environment variable values?

**Comment by mitchellh** [comment]
We've talked about the idea of parameterized dependencies but we don't have any good idea for how to do this yet. I'm open for a discussion about it.

The main challenge is that dependencies are meant to describe singleton things (for now). If we parameterize these, how are we supposed to differentiate two different people depending on a service with two different settings? Do we deploy two? etc. 

For now, I'm going to say we won't support this use case until it becomes more prevalant, but I'm open to more ideas.
