### ISSUE TITLE
Allow for customization of vagrant box etc.

### ISSUE THREAD

**Issue by chiefy** [hashicorp/otto#142]
I understand you can customize your `Vagrantfile` by:
```hcl
...
customization "dev" {
    vagrantfile = "./Vagrantfile"
}
...
```

In my case, we already have a base box in Atlas we'd like to use, but it's already provisioned etc, so really all we need to change is the box type:
```hcl
...
customization "dev" {
    box = "mycompany/trusty"
}
...
```

**Comment by jrnt30** [comment]
Can your Vagrantfile just reference that base box similar to how you would use it locally?

**Comment by chiefy** [comment]
@jrnt30 yes, but it seems silly to have to use a whole custom `Vagrantfile` for one line of customization.

**Comment by jrnt30** [comment]
Yeah, agreed.  Just curious if it worked as you expected.

**Comment by mitchellh** [comment]
I think we want to stick with custom Vagrantfiles rather than box and lowering that granularity. Over time we'll also expose a couple options for operating systems.

**Comment by chiefy** [comment]
@mitchellh yeah, I suppose it is a slippery slope once you start adding `Appfile` options for certain overrides to `Vagrantfile`.

One question though: any reason you're using 12.04 LTS instead of 14.04 LTS (the latest LTS)?
