### ISSUE TITLE
Docker application dependency run_args not being copied into compiled Vagrantfile

### ISSUE THREAD

**Issue by davidwinter** [hashicorp/otto#143]
I created a MySQL dependency file within my otto test project under the directory `mysql/Appfile`:

```
application {
    name = "mysql"
    type = "docker-external"
}

customization "mysql" {
    image = "mysql"
    run_args = "-e MYSQL_ROOT_PASSWORD=my-secret-pw -e MYSQL_DATABASE=localdev -p 3306:3306"
}
```

And then referenced this in my main `Appfile`:

```
application {
  name = "testproject"
  type = "ruby"

  dependency { source = "mysql" }
}
```

When I run `otto compile`, the `run_args` weren't included in the `.otto/compiled/app/dev/Vagrantfile`, and the value remained empty:

```
config.vm.provision "docker" do |d|
  d.run "mysql", args: "", image: "mysql"
end
```

In order to get it working as expected, I had to manually add them in:

```
config.vm.provision "docker" do |d|
  d.run "mysql", args: "-e MYSQL_ROOT_PASSWORD=my-secret-pw -e MYSQL_DATABASE=localdev -p 3306:3306", image: "mysql"
end
```

**Comment by jrnt30** [comment]
I believe it should be `customization "docker"` instead of `customization "mysql"`

**Comment by davidwinter** [comment]
Thanks @jrnt30

**Comment by lhm** [comment]
@jrnt30 I just ran into a similar issue, albeit using `customization "docker" {...}` - which isn't working any more. It's now only `customization {...}` as stated [here](https://www.ottoproject.io/docs/apps/docker-external/customization.html). However, the [main example](https://www.ottoproject.io/docs/apps/docker-external/index.html) for docker-external still shows the old syntax. This should maybe be fixed as it is misleading.
