### ISSUE TITLE
Otto does not automatically install the app

### ISSUE THREAD

**Issue by FooBarWidget** [hashicorp/otto#150]
Currently, 'otto dev' creates a development environment, e.g. a VM with Ruby installed. However it does not:

 - Install dependencies (bundle install, npm install)
 - Start a server

I started using Otto without reading the docs. I was expected that after running 'otto dev', I can immediately open the IP address in my browser and see my app. That wasn't the case. Although this is documented, I found it a bit counter-intuitive.

Wouldn't it be a good idea to have Otto install the app too so that 'otto dev' is truly turnkey?

**Comment by justincampbell** [comment]
@FooBarWidget Thanks! I'm currently working on this. We'll definitely bundle during `otto dev`, but we'll be introducing an `otto dev start` command in the near future that should better fit the use case of starting Rails server.

**Comment by FooBarWidget** [comment]
Maybe just use Passenger in development too? That way you don't have to start a server; Passenger will take care of keeping the app running.

**Comment by justincampbell** [comment]
@FooBarWidget We now bundle automatically. A rails apptype is coming shortly, which will setup db/migrations. We're still trying to decide on the best course for starting app servers.
