### ISSUE TITLE
Customizing PHP app web root using Appfile

### ISSUE THREAD

**Issue by themccallister** [hashicorp/otto#164]
When building a custom PHP application, is there a way to define the web root for the project if my directory structure looks like so?

```
- Appfile
- composer.json
- composer.lock
- public
- vendor
```

Currently the default is to load the root of the app as the web root. 

Would it be more efficient for otto to detect directories with the `index.php` file as the "root" or perhaps look for a sensible default such as `public` or `web`?

**Comment by jmetzmeier** [comment]
This looks like a duplicate of #152.

**Comment by themccallister** [comment]
Definitely, I'll close this as a dupe.

**Comment by guycalledseven** [comment]
this is dupe of https://github.com/hashicorp/otto/issues/152 (#265 is dupe as well)
