### ISSUE TITLE
wrong ***.service.consul IP

### ISSUE THREAD

**Issue by miroshnik** [hashicorp/otto#166]
vagrant@precise64:/vagrant$ dig +short mysql.service.consul
10.0.2.15
vagrant@precise64:/vagrant$ docker inspect mysql | grep IPAddress
        "IPAddress": "172.17.0.1",
        "SecondaryIPAddresses": null,

**Comment by d4v3y0rk** [comment]
I think that 10.0.2.15 IP is related to the virtualbox NAT. I have the exact same IP in my virtualbox logs for the docker-machine `default`
```
25:06:01.550961 NAT: DHCP offered IP address 10.0.2.15
```

**Comment by miroshnik** [comment]
The main problem, I can't connect to mysql.service.consul, but to 172.17.0.1:3306 can.

**Comment by mitchellh** [comment]
We should be forwarding the port with Docker, so we don't output the container IP address. Can you check the Docker config?
