### ISSUE TITLE
Custom app type Vagrant dev shares broken

### ISSUE THREAD

**Issue by ilkka** [hashicorp/otto#170]
After slightly hackishly getting the custom app type to work as described in #168, I noticed that my shares were broken. This seems to be because the working directory for Vagrant is is `.otto/compiled/app/dev`. Since the shares are defined with relative paths, my app code from the root of the repo doesn't appear in the box, and I only see whatever `otto compile` put there.

**Comment by mitchellh** [comment]
Fixed (docs issue). See my commit for more info!
