### ISSUE TITLE
Commands inconsistency. Add "otto dev halt" top level command.

### ISSUE THREAD

**Issue by iJackUA** [hashicorp/otto#171]
Currently it supposes such a command chains
`otto dev`  - runs 'vagrant up' internally + some magic of course :)
`otto dev ssh`  - runs 'vagrant ssh' internally
`otto dev destroy`  - runs 'vagrant destroy' internally
`otto dev vagrant halt`  - runs 'vagrant ssh' internally - **and this is not obvious**

But `vagrant up` / `vagrant halt` are 2 the most frequent commands during normal dev flow.

**At my point of view a "shortcut" `otto dev halt` is need.**

**Comment by toonketels** [comment]
Yes, would be my expectation also.
