### ISSUE TITLE
otto dev does not work with Parallels

### ISSUE THREAD

**Issue by ragusource** [hashicorp/otto#177]
The following error happens when using Parallels:

$ otto dev
==> Creating local development environment with Vagrant if it doesn't exist...
    Raw Vagrant output will begin streaming in below. Otto does
    not create this output. It is mirrored directly from Vagrant
    while the development environment is being created.

Bringing machine 'default' up with 'parallels' provider...
==> default: Box 'hashicorp/precise64' could not be found. Attempting to find and install...
    default: Box Provider: parallels
    default: Box Version: >= 0
==> default: Loading metadata for box 'hashicorp/precise64'
    default: URL: https://atlas.hashicorp.com/hashicorp/precise64
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Atlas, make sure the box is
released.

Name: hashicorp/precise64
Address: https://atlas.hashicorp.com/hashicorp/precise64
Requested provider: [:parallels]

Error building dev environment: Error executing Vagrant: exit status 1

The error messages from Vagrant are usually very informative.
Please read it carefully and fix any issues it mentions. If
the message isn't clear, please report this to the Otto project.

**Comment by legal90** [comment]
It was fixed by #85, but not released yet

**Comment by ragusource** [comment]
Is there any kind of ETA on the release?

**Comment by mitchellh** [comment]
Very soon, within a couple weeks. Thanks!
