### ISSUE TITLE
Support import Vagrantfile

### ISSUE THREAD

**Issue by ilyar** [hashicorp/otto#186]
I am sure it will be convenient to be able to use an external Vagrantfile, like so:
```hcl
customization "dev" {
    vagrantfile = "github.com/ilyar/localserver/Vagrantfile"
}
```

**Comment by selimekizoglu** [comment]
Is [this](https://www.ottoproject.io/docs/apps/custom/customization.html) what you're talking about?

**Comment by onceatime** [comment]
and if possible also a dynamic tpl version
````
customization "dev" {
    vagrantfile = "github.com/ilyar/localserver/Vagrantfile.tpl"
}
````

**Comment by mitchellh** [comment]
This could potentially be useful but I want to wait on this. I think this is a better fit for Git submodules or something and I'd rather just point to those locally. If this use case keeps popping up then I'll cater to it.
