### ISSUE TITLE
Issue with Ruby customization for 1.9.3

### ISSUE THREAD

**Issue by adamyonk** [hashicorp/otto#188]
In a `ruby` application with:
```
customization "ruby" {
  ruby_version = "1.9.3"
}
```
I see this towards the end of `otto dev`:
```
==> default: Oct  2 14:32:31 precise64 otto: E: Unable to locate package ruby1.9.3-dev
==> default: Oct  2 14:32:31 precise64 otto: E: Couldn't find any package by regex 'ruby1.9.3-dev'
```

I can only find a `ruby1.9.3` package in apt-cache (no `ruby1.9.3-dev`).
```
vagrant@precise64:/vagrant$ sudo apt-cache search ruby1.9.3
ruby1.9.3 - Interpreter of object-oriented scripting language Ruby, version 1.9.3
```

Is there some way to get it to not look for -dev when installing, or does a special case need to be written for that?

**Comment by justincampbell** [comment]
Ruby 1.9.3 was end-of-lifed earlier this year: https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/

I'm not necessarily against supporting this, but just wanted to point that out.

**Comment by adamyonk** [comment]
Ah, gotcha. What are best-practices for setting up a post-install something or other for cases like that?

**Comment by justincampbell** [comment]
@adamyonk Can you try `ruby_version = "1.9.1"`. It seems that Ruby NG includes 1.9.3 in the ruby1.9.1 package https://launchpad.net/~brightbox/+archive/ubuntu/ruby-ng

**Comment by adamyonk** [comment]
1.9.1 is available, thanks. I am curious about how to control things like that (things that customization blocks don't cover). Is there a best practice for that?

**Comment by mitchellh** [comment]
For completely custom Ruby installations we don't support anything yet but I can imagine exposing a customization that allows for this (just... arbitrary shell script probably).

**Comment by mitchellh** [comment]
Pushed website change to doc this
