### ISSUE TITLE
Installing Binary Packages

### ISSUE THREAD

**Issue by danielgroves** [hashicorp/otto#196]
This may be my lack of understanding, so please do feel free to send me on my way if necessary. 

I've got a ruby project running in seconds (amazing work there, thank you!), but one of my dependencies of it is ImageMagick. Now, I know I could install this by running:

```
otto dev ssh
sudo apt-get update -y
sudo apt-get install imagemagick
```

And this would then work fine, however having to do this manually seems like the wrong approach to me. Half the point of this is to ensure everyone has the same working development environment, after all. 

I could install this by building a separate docker container, however as I understand it Docker won't allow one container to access binaries in another, only services which communicate over a socket or http. 

So what's the best approach to make this binary available? Do I need to setup a custom Vagrantfile and provision this myself, or is there another approach for dependencies of this sort?

Thanks,

Dan.

**Comment by jrnt30** [comment]
You're right that the binary wouldn't be available from the docker container if you installed it there.  There is some work being done in #133 to allow you to customize a requirement to a given package to be installed.  For now I would assume that would be the easiest solution if there is a dependency that relies on it.

**Comment by danielgroves** [comment]
Thanks @jrnt30. I've subscribed to that thread, I'll close this issue on the basis that their's a fix coming. 

Thanks again for a speedy response, especially on the weekend!

**Comment by jrnt30** [comment]
You may want to issue a pull request, I am not familiar with that package, but the current thread does not install that package explicitly.  If you have a dependency -> package you want included you could issue a quick PR.

**Comment by danielgroves** [comment]
I actually noticed through #133 the libraries behind the CLI utility are [already installed for RMagick](https://github.com/hashicorp/otto/blob/master/builtin/app/ruby/data/common/dev/Vagrantfile.tpl#L123). I tested for it by trying a CLI command for it, which isn't available, but the libraries required by RMagick already are. Partly me being dopey and not thinking it through!
