### ISSUE TITLE
PHP projects ... but no webserver

### ISSUE THREAD

**Issue by PhillippOhlandt** [hashicorp/otto#199]
Hey,

I tested Otto with a clean installation of laravel. Otto installed PHP and Composer on the Vagrant box but no webserver. 

Can someone explain me the logic behind this? 

Thought the concept of Otto is to detect the application type (first it thought laravel is a node.js application) and create the environment to run this application (PHP application without webserver ... hmm).

**Comment by juice49** [comment]
I think you need to start your app using PHP's built in web server after starting Otto. On creating a PHP box, Otto tells me: 

> For example, if you start your app with 'php -S 0.0.0.0:5000', then you can access it using the above IP at port 5000.

I'm not sure if there's a way to run scripts automatically when starting an Otto box, but it'd be very handy for starting PHP's server automatically.

**Comment by PhillippOhlandt** [comment]
That would be ok for development. But what when you deploy the thing? Then you have to setup and configure nginx by your own. That would make Otto pretty useless.

**Comment by juice49** [comment]
Ah sorry, good point, I was only thinking about it from a development point of view.

**Comment by mitchellh** [comment]
For deployment we install Apache and mod_php. Development we ask the user to use a server directly.

**Comment by PhillippOhlandt** [comment]
Apache, really?

**Comment by mitchellh** [comment]
If you'd like to improve it please contribute! This is the idea behind Otto. We just did what we could to get folks started, and if you can articulate why that isn't a best practice and something else is better, then we'd be happy to bring it in.

**Comment by PhillippOhlandt** [comment]
I just thing nginx with php-fpm would be better. It's much faster than Apache with mod_php. And the development box should have that too.

**Comment by mitchellh** [comment]
Given that we're not PHP developers, I believe you. :) Do you mind helping us by doing that? I'm happy to take a look shortly too.

**Comment by PhillippOhlandt** [comment]
I would but I am not a GO developer =(

**Comment by mitchellh** [comment]
@PhillippOhlandt No problem. Can you articulate or link to best practices setup and we can use your knowledge and our Go expertise to get it in?

**Comment by PhillippOhlandt** [comment]
Yes, I'll give you all informations tomorrow or in the next days (linux packages and nginx conf).
