### ISSUE TITLE
Problem doing getting started

### ISSUE THREAD

**Issue by AresDev** [hashicorp/otto#200]
Hello,

I was following the getting started on a macosx "El Capitan" and when I was triying to do otto dev ssh I got the error:

Malformed version: 1.7.4/lib/vagrant/pre-rubygems.rb:31

Then I decided to start over again and deleted the folder of the getting started and the virtualbox machine, and now it doesn´t created and when I run otto dev it shows me again the error:

Error building dev environment: Malformed version: 1.7.4/lib/vagrant/pre-rubygems.rb:31

What should I do?

Thnks!

**Comment by mitchellh** [comment]
Can you get the `OTTO_LOG=1` output of this please? Thanks!

**Comment by AresDev** [comment]
2015/10/03 21:21:05 [INFO] Otto version: 0.1.1  b4be6e9033ef2bf53ab2058ae956ef08125c7fa9+CHANGES
2015/10/03 21:21:05 Detected home directory from env var: /Users/AresDev
2015/10/03 21:21:05 [DEBUG] reading IP, cache path: /Users/AresDev/Developer/Tests/otto/otto-getting-started/.otto/data/dev_ip
2015/10/03 21:21:05 [DEBUG] read ip from cache: 172.16.1.126
2015/10/03 21:21:05 [INFO] Loading app implementation for Tuple: ("ruby", "aws", "simple")
2015/10/03 21:21:05 [DEBUG] reading IP, cache path: /Users/AresDev/Developer/Tests/otto/otto-getting-started/.otto/data/dev_ip
2015/10/03 21:21:05 [DEBUG] read ip from cache: 172.16.1.126
2015/10/03 21:21:05 [INFO] Loading app implementation for Tuple: ("ruby", "aws", "simple")
2015/10/03 21:21:05 [DEBUG] installIfNeeded: vagrant
Error building dev environment: Malformed version: 1.7.4/lib/vagrant/pre-rubygems.rb:31:

**Comment by mitchellh** [comment]
Actually, this is fixed in master. If you're comfortable compiling from scratch give that a shot. Otherwise, I'm sure it is fixed.
