### ISSUE TITLE
SSH key not found

### ISSUE THREAD

**Issue by gustavoandrescabral** [hashicorp/otto#216]
Hi there

I got this error message when I run ```otto infra```:

```
Error occurred: Otto uses your SSH Agent to authenticate with instances created in
AWS, but it could not verify that your SSH key is loaded into the agent.
The error message follows:

Error parsing provided public key: ssh: no key found
```

I've put my credentials of AWS, then I wrote my decrypt password and finally got this failure.

Some help please

**Comment by jrnt30** [comment]
Had a few issues with this myself initially.  To just set expectations, the infrastructure configuration expects four things: 
- AWS Access Key 
- AWS Secret Key 
- The path to the *public* half of your ssh key
- The *private* half of your ssh key to be added to your ssh agent via `ssh-add`

One thing to note is that if you let AWS setup your keypair, you will only have the private half of the keypair.  You can generate the public half however [as noted here](https://github.com/hashicorp/otto/issues/144#issuecomment-144449657)

**Comment by gustavoandrescabral** [comment]
@jrnt30 I have question? When do I have to create both id_rsa and id_rsa.pub? Are these two files created when I run ```otto infra```? I'm really confused, those files doesn't exist in my system

**Comment by jrnt30** [comment]
The key is used under the covers by Packer so that the AMI is accessible and you are able to log into it.  I have not dug into that part of the Otto code to see if it will generate a default ssh key if it doesn't exist, but I typically manage the keys myself.  

My suggestion if you don't want to dig into the code is to just create a keypair prior to running the infra.  There is an existing issue #118 to update existing infra config, but it has not been implemented yet.

**Comment by gustavoandrescabral** [comment]
@jrnt30 yours answers have been so useful for me, I'm so grateful. But I have to request you a last answer (for the sake of god): If I generate a key pair with the ```ssh-keygen``` command, how do I put those in my aws account and I use those 'uploaded keys' as Access Keys for an user in IAM?

**Comment by jrnt30** [comment]
Yeah, you would upload the public half of the keypair.  Directions here at http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html#how-to-generate-your-own-key-and-import-it-to-aws

**Comment by gustavoandrescabral** [comment]
Nice
