### ISSUE TITLE
Using Otto to deploy the same project multiple times

### ISSUE THREAD

**Issue by Pixcell** [hashicorp/otto#221]
Hi,

We'd like to use Otto to deploy our solution on AWS, but we need to be able to create multiple virtual machines, using the same otto project.
We'd like to have an option to create multiple infras, with the exact same configuration.

**Comment by jrnt30** [comment]
@Pixcell I believe this is currently reported as #161

**Comment by Pixcell** [comment]
Thank you for the answer, yes multiple 'environments' could be a working trick. But it is not exactly what we are looking for, we need to build and deploy the same project multiple times, on multiple AWS (configured the same way).

**Comment by justincampbell** [comment]
@Pixcell how do the deployments vary?

**Comment by Pixcell** [comment]
They do not vary, that's the issue.
The idea is: 
We have a solution running on virtual machines, and we want to automate the deployment of our solution. We need to be able to create multiple instances of AWS, and deploy our solution on it.
We though Otto could be very usefull, but we are stuck.

**Comment by sean-bennett112** [comment]
Not sure if this is what @Pixcell is going for, but our example where this would be nice is for enterprise customers. We have multiple enterprise deployments of the same base project that are virtually identical, minus minimal config changes (keys, etc).

We'd like to be able to describe multiple copies of the same project, give them separate names (customerA, customerB, etc.), and potentially pass config information, potentially via consul, into those separate enterprise deployments.

Environments might work for this, though I feel like conflating the two scenarios of enterprise customers and testing/staging/prod environments... well it just feels a little weird to me. Not to say it's a bad solution, however. Anyway, just wanted to point out this use case.

**Comment by jrnt30** [comment]
@sean-bennett112 Yeah, well said.  That is essentially our hope/expectation as well.  Based upon Mitchell's comment about having an arbitrary number of environments, I would assume that our expectations are not far off.

**Comment by mitchellh** [comment]
There is a lot of good discussion here, but #161 is the issue. In the meantime you can work around it by copying your directory (not ideal, but works).
