### ISSUE TITLE
otto.exe for Windows 64 fails immediately

### ISSUE THREAD

**Issue by tn3rb** [hashicorp/otto#223]
Downloaded: otto_0.1.1_windows_amd64
extracted then double clicked otto.exe
small window flashes on screen for less than a second
then nothing... 
except a tear on my cheek and an emptiness in my heart...
:(
otto is NOT available on the PATH

Already installed:
Vagrant 1.7.4
Virtual Box 5.0.6 r103037

System
Windows 10
Processor: Intel i7-2600 3.4Ghz x64-based
Ram: 16 GB

**Comment by jrnt30** [comment]
I don't believe the EXE is a visual thing and without terminal input it would simply display the error message and terminate immediately.  Did you try going into powershell or cmd and running executing the EXE directly? 

Without modifying your path, you're right, Otto would not be available. Try CDing into the directory and executing `./otto.exe compile` directly.

**Comment by justincampbell** [comment]
@tn3rb Can you try running it from the command line? I think on Windows if you press the start menu and then start typing "command", and then inside of that black window, run `otto.exe`. You may need to move to the directory you unzipped it to using `cd`.

**Comment by justincampbell** [comment]
@jrnt30 beat me to it

**Comment by tn3rb** [comment]
i had tried just running "otto.exe" from the cmd line but that just showed the standard help options.

otto.exe compile did the trick 

YAY !!!

 !!!!!!!!!!!!!!!!!!!!!!!!!!! OTTO CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

:(

here's the log output:


2015/10/07 09:33:59 [INFO] Otto version: 0.1.1  b4be6e9033ef2bf53ab2058ae956ef08125c7fa9+CHANGES
2015/10/07 09:33:59 [DEBUG] loading detectors from: C:\Users\tn3rb\.otto.d\detect
2015/10/07 09:33:59 [DEBUG] compiling dependencies for: Downloads
2015/10/07 09:33:59 [INFO] deleting prior compilation contents: C:\Users\tn3rb\Downloads\.otto\compiled
2015/10/07 09:33:59 [INFO] running infra compile...
2015/10/07 09:33:59 [DEBUG] Copying all assets: data/simple => C:\Users\tn3rb\Downloads\.otto\compiled\infra-Downloads
2015/10/07 09:33:59 [DEBUG] Copying asset: main.tf
2015/10/07 09:33:59 [DEBUG] Copying asset: outputs.tf
2015/10/07 09:33:59 [INFO] running foundation compilations
2015/10/07 09:33:59 [DEBUG] Copying all assets: data/common => C:\Users\tn3rb\Downloads\.otto\compiled\foundation-consul
2015/10/07 09:33:59 [DEBUG] Copying asset: app-dev
2015/10/07 09:33:59 [DEBUG] Copying all assets: data/common/app-dev => C:\Users\tn3rb\Downloads\.otto\compiled\foundation-consul\app-dev
2015/10/07 09:33:59 [DEBUG] Copying asset: upstart.conf
2015/10/07 09:33:59 [DEBUG] Copying asset: main.sh.tpl
2015/10/07 09:33:59 [DEBUG] Copying asset: app-dev-dep
2015/10/07 09:33:59 [DEBUG] Copying all assets: data/common/app-dev-dep => C:\Users\tn3rb\Downloads\.otto\compiled\foundation-consul\app-dev-dep
2015/10/07 09:33:59 [DEBUG] Copying asset: main.sh.tpl
2015/10/07 09:33:59 [DEBUG] Copying asset: deploy
2015/10/07 09:33:59 [DEBUG] Copying all assets: data/common/deploy => C:\Users\tn3rb\Downloads\.otto\compiled\foundation-consul\deploy
2015/10/07 09:33:59 [DEBUG] Copying asset: module-aws
2015/10/07 09:33:59 [DEBUG] Copying all assets: data/common/deploy/module-aws => C:\Users\tn3rb\Downloads\.otto\compiled\foundation-consul\deploy\module-aws
2015/10/07 09:33:59 [DEBUG] Copying asset: join.sh
2015/10/07 09:33:59 [DEBUG] Copying asset: main.tf
2015/10/07 09:33:59 [DEBUG] Copying asset: outputs.tf
2015/10/07 09:33:59 [DEBUG] Copying asset: variables.tf
2015/10/07 09:33:59 [DEBUG] Copying asset: module-aws-simple
2015/10/07 09:33:59 [DEBUG] Copying all assets: data/common/deploy/module-aws-simple => C:\Users\tn3rb\Downloads\.otto\compiled\foundation-consul\deploy\module-aws-simple
2015/10/07 09:33:59 [DEBUG] Copying asset: main.tf
2015/10/07 09:33:59 [DEBUG] Copying asset: outputs.tf
2015/10/07 09:33:59 [DEBUG] Copying asset: setup.sh
2015/10/07 09:33:59 [DEBUG] Copying asset: variables.tf
2015/10/07 09:33:59 [DEBUG] Copying asset: app-build
2015/10/07 09:33:59 [DEBUG] Copying all assets: data/common/app-build => C:\Users\tn3rb\Downloads\.otto\compiled\foundation-consul\app-build
2015/10/07 09:33:59 [DEBUG] Copying asset: main.sh.tpl
2015/10/07 09:33:59 [DEBUG] Copying asset: upstart.conf.tpl
2015/10/07 09:33:59 [DEBUG] Copying asset: app-deploy
2015/10/07 09:33:59 [DEBUG] Copying all assets: data/common/app-deploy => C:\Users\tn3rb\Downloads\.otto\compiled\foundation-consul\app-deploy
2015/10/07 09:33:59 [DEBUG] Copying asset: main.sh.tpl
2015/10/07 09:33:59 [DEBUG] Copying all assets: data/aws-simple => C:\Users\tn3rb\Downloads\.otto\compiled\foundation-consul
2015/10/07 09:33:59 [DEBUG] Copying asset: deploy
2015/10/07 09:33:59 [DEBUG] Copying all assets: data/aws-simple/deploy => C:\Users\tn3rb\Downloads\.otto\compiled\foundation-consul\deploy
2015/10/07 09:33:59 [DEBUG] Copying asset: main.tf
2015/10/07 09:33:59 [DEBUG] Copying asset: variables.tf
2015/10/07 09:33:59 [DEBUG] reading IP, cache path: C:\Users\tn3rb\Downloads\.otto\data\dev_ip
2015/10/07 09:33:59 [DEBUG] no ip cache found, getting new IP
panic: no subnet

goroutine 35 [running]:
github.com/hashicorp/otto/helper/localaddr.(*DB).Next.func1(0xc08216d380, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/otto/helper/localaddr/db.go:69 +0x15f
github.com/boltdb/bolt.(*DB).Update(0xc082173040, 0xc0821418b8, 0x0, 0x0)
	/opt/gopath/src/github.com/boltdb/bolt/db.go:547 +0xba
github.com/hashicorp/otto/helper/localaddr.(*DB).Next(0xc08226e060, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/otto/helper/localaddr/db.go:127 +0x10d
github.com/hashicorp/otto/helper/localaddr.(*CachedDB).IP(0xc082141be8, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/otto/helper/localaddr/db_cached.go:59 +0x4f2
github.com/hashicorp/otto/otto.(*Core).appContext(0xc08218e180, 0xc082073300, 0xc082277ec8, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/otto/otto/core.go:773 +0xc1a
github.com/hashicorp/otto/otto.(*Core).walk.func1(0x97b300, 0xc082125e60, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/otto/otto/core.go:229 +0x11a
github.com/hashicorp/terraform/dag.(*AcyclicGraph).Walk.func3(0xc082169fe0, 0xc0821d9470, 0xc082169ff0, 0xc0821d94a0, 0xc08226e000, 0x97b300, 0xc082125e60, 0xc0822130e0, 0xc082213140)
	/opt/gopath/src/github.com/hashicorp/terraform/dag/dag.go:238 +0xf6
created by github.com/hashicorp/terraform/dag.(*AcyclicGraph).Walk
	/opt/gopath/src/github.com/hashicorp/terraform/dag/dag.go:247 +0x71b

goroutine 1 [chan receive]:
github.com/hashicorp/terraform/dag.(*AcyclicGraph).Walk(0xc082125b00, 0xc0821d9470, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/dag/dag.go:250 +0x766
github.com/hashicorp/otto/otto.(*Core).walk(0xc08218e180, 0xc082179590, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/otto/otto/core.go:244 +0x24d
github.com/hashicorp/otto/otto.(*Core).Compile(0xc08218e180, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/otto/otto/core.go:196 +0x7df
github.com/hashicorp/otto/command.(*CompileCommand).Run(0xc0820e1ec0, 0xc082008650, 0x0, 0x0, 0xc0820e6568)
	/opt/gopath/src/github.com/hashicorp/otto/command/compile.go:187 +0x207f
github.com/mitchellh/cli.(*CLI).Run(0xc08209c2c0, 0xc08209c2c0, 0x0, 0x0)
	/opt/gopath/src/github.com/mitchellh/cli/cli.go:112 +0x65c
main.wrappedMain(0xc082067ec0)
	/opt/gopath/src/github.com/hashicorp/otto/main.go:126 +0x5cc
main.realMain(0x0)
	/opt/gopath/src/github.com/hashicorp/otto/main.go:88 +0xcb0
main.main()
	/opt/gopath/src/github.com/hashicorp/otto/main.go:18 +0x1f

goroutine 5 [syscall]:
os/signal.loop()
	/opt/go/src/os/signal/signal_unix.go:22 +0x1f
created by os/signal.init.1
	/opt/go/src/os/signal/signal_unix.go:28 +0x3e

goroutine 6 [chan receive]:
main.initSignalHandlers.func1(0xc08200c960)
	/opt/gopath/src/github.com/hashicorp/otto/signal.go:19 +0x3d
created by main.initSignalHandlers
	/opt/gopath/src/github.com/hashicorp/otto/signal.go:22 +0xda

goroutine 7 [select]:
net/http.(*Transport).getConn(0xc08205a090, 0xc0821360e0, 0x0, 0xc082122120, 0x5, 0xc08211e220, 0x20, 0x0, 0x0, 0x0)
	/opt/go/src/net/http/transport.go:554 +0x66a
net/http.(*Transport).RoundTrip(0xc08205a090, 0xc0821360e0, 0xd2, 0x0, 0x0)
	/opt/go/src/net/http/transport.go:228 +0x4b3
net/http.send(0xc0821360e0, 0x2a14440, 0xc08205a090, 0xc0821221b0, 0x0, 0x0)
	/opt/go/src/net/http/client.go:220 +0x533
net/http.(*Client).send(0xd374a0, 0xc0821360e0, 0x85, 0x0, 0x0)
	/opt/go/src/net/http/client.go:143 +0x161
net/http.(*Client).doFollowingRedirects(0xd374a0, 0xc0821360e0, 0xb602e8, 0x0, 0x0, 0x0)
	/opt/go/src/net/http/client.go:380 +0xbc7
net/http.(*Client).Do(0xd374a0, 0xc0821360e0, 0xa, 0x0, 0x0)
	/opt/go/src/net/http/client.go:175 +0xa3
github.com/hashicorp/go-checkpoint.Check(0xc08202df00, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/go-checkpoint/checkpoint.go:145 +0xa64
main.runCheckpoint(0xc0820dcf10)
	/opt/gopath/src/github.com/hashicorp/otto/checkpoint.go:51 +0x419
created by main.wrappedMain
	/opt/gopath/src/github.com/hashicorp/otto/main.go:104 +0x295

goroutine 8 [semacquire]:
sync.runtime_Syncsemacquire(0xc0820d8580)
	/opt/go/src/runtime/sema.go:237 +0x20f
sync.(*Cond).Wait(0xc0820d8570)
	/opt/go/src/sync/cond.go:62 +0xa2
io.(*pipe).read(0xc0820d8540, 0xc0820d7000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/opt/go/src/io/pipe.go:52 +0x2d9
io.(*PipeReader).Read(0xc0820260e8, 0xc0820d7000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/opt/go/src/io/pipe.go:134 +0x57
bufio.(*Scanner).Scan(0xc082072700, 0x0)
	/opt/go/src/bufio/scan.go:180 +0x87e
github.com/hashicorp/otto/command.(*Meta).FlagSet.func1(0xc082072700, 0xc0820e1ec0)
	/opt/gopath/src/github.com/hashicorp/otto/command/meta.go:165 +0x2c
created by github.com/hashicorp/otto/command.(*Meta).FlagSet
	/opt/gopath/src/github.com/hashicorp/otto/command/meta.go:168 +0x35f

goroutine 17 [IO wait]:
net.runtime_pollWait(0x2e41060, 0x77, 0xc0821042c0)
	/opt/go/src/runtime/netpoll.go:157 +0x67
net.(*pollDesc).Wait(0xc08213a5f0, 0x77, 0x0, 0x0)
	/opt/go/src/net/fd_poll_runtime.go:73 +0x41
net.(*ioSrv).ExecIO(0xc08212e028, 0xc08213a568, 0xa631a0, 0x9, 0xb600e8, 0x0, 0x0, 0x0)
	/opt/go/src/net/fd_windows.go:182 +0x177
net.(*netFD).connect(0xc08213a480, 0x2e40138, 0xc08211e3e0, 0x2e40138, 0xc08211e3c0, 0xecda74081, 0x1f1ad355, 0xd37580, 0x0, 0x0)
	/opt/go/src/net/fd_windows.go:355 +0x615
net.(*netFD).dial(0xc08213a480, 0x2e400f0, 0x0, 0x2e400f0, 0xc08210a3c0, 0xecda74081, 0x1f1ad355, 0xd37580, 0x0, 0x0)
	/opt/go/src/net/sock_posix.go:137 +0x358
net.socket(0xa5e208, 0x3, 0x2, 0x1, 0x0, 0xc08210a300, 0x2e400f0, 0x0, 0x2e400f0, 0xc08210a3c0, ...)
	/opt/go/src/net/sock_posix.go:89 +0x372
net.internetSocket(0xa5e208, 0x3, 0x2e400f0, 0x0, 0x2e400f0, 0xc08210a3c0, 0xecda74081, 0x5b1f1ad355, 0xd37580, 0x1, ...)
	/opt/go/src/net/ipsock_posix.go:160 +0x148
net.dialTCP(0xa5e208, 0x3, 0x0, 0xc08210a3c0, 0xecda74081, 0xc01f1ad355, 0xd37580, 0x462c10, 0x0, 0x0)
	/opt/go/src/net/tcpsock_posix.go:171 +0x125
net.dialSingle(0xc08211c180, 0x2e40060, 0xc08210a3c0, 0xecda74081, 0x1f1ad355, 0xd37580, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/net/dial.go:364 +0x3fc
net.dialSerial.func1(0xecda74081, 0x1f1ad355, 0xd37580, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/net/dial.go:336 +0x7c
net.dial(0xa5e208, 0x3, 0x2e40060, 0xc08210a3c0, 0xc08211e380, 0xecda74081, 0x1f1ad355, 0xd37580, 0x0, 0x0, ...)
	/opt/go/src/net/fd_windows.go:86 +0x113
net.dialSerial(0xc08211c180, 0xc0820fa3c0, 0x3, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/net/dial.go:338 +0x7d7
net.(*Dialer).Dial(0xc08200a4b0, 0xa5e208, 0x3, 0xc08211e220, 0x20, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/net/dial.go:232 +0x516
net.(*Dialer).Dial-fm(0xa5e208, 0x3, 0xc08211e220, 0x20, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/net/http/transport.go:38 +0x75
net/http.(*Transport).dial(0xc08205a090, 0xa5e208, 0x3, 0xc08211e220, 0x20, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/net/http/transport.go:499 +0x80
net/http.(*Transport).dialConn(0xc08205a090, 0x0, 0xc082122120, 0x5, 0xc08211e220, 0x20, 0xa585b8, 0x0, 0x0)
	/opt/go/src/net/http/transport.go:596 +0x19b0
net/http.(*Transport).getConn.func4(0xc08205a090, 0x0, 0xc082122120, 0x5, 0xc08211e220, 0x20, 0xc082118300)
	/opt/go/src/net/http/transport.go:549 +0x6d
created by net/http.(*Transport).getConn
	/opt/go/src/net/http/transport.go:551 +0x26c

goroutine 33 [runnable]:
sync.runtime_Semacquire(0xc082169fec)
	/opt/go/src/runtime/sema.go:43 +0x2d
sync.(*WaitGroup).Wait(0xc082169fe0)
	/opt/go/src/sync/waitgroup.go:126 +0xbb
github.com/hashicorp/terraform/dag.(*AcyclicGraph).Walk.func1(0xc082213080, 0xc082169fe0)
	/opt/gopath/src/github.com/hashicorp/terraform/dag/dag.go:173 +0x4f
created by github.com/hashicorp/terraform/dag.(*AcyclicGraph).Walk
	/opt/gopath/src/github.com/hashicorp/terraform/dag/dag.go:174 +0x101

**Comment by johnyesberg** [comment]
To use otto on windows, I've tried the following steps so far:
- Download otto
- Ensure otto is on the path. (I like to use the excellent ```patheditor``` utility.)
- Download and install vagrant
- Ensure vagrant is on the path
- Download virtualbox
- Ensure virtualbox is on the path
- Download git (required to install the getting started demo)
- Ensure git /cmd and /bin directories are both on the path. (The /cmd directory is required for ssh commands and bash)
- Create ssh key pair using https://help.github.com/articles/generating-ssh-keys/
- Run bash
- Run ssh-agent, and copy-and-paste the two environment-variable-setting commands into the shell
- Run ssh-add to add public key to ssh-agent

I had planned to write up a nice blog post to describe all this, but it's not working yet. Otto infra is still complaining that it can't connect to ssh-agent using a unix-style socket. The github link above has a test of ssh-agent, which indicates it is working successfully. It's therefore disappointing to see that otto is having trouble.
```
bash-3.1$ otto infra
==> Detecting infrastructure credentials for: otto-getting-started (aws)
    Cached and encrypted infrastructure credentials found.
    Otto will now ask you for the password to decrypt these
    credentials.

Encrypted Credentials Password
  Infrastructure credentials are required for this operation. Otto found
  saved credentials that are password protected. Please enter the password
  to decrypt these credentials. You may also just hit <enter> and leave
  the password blank to force Otto to ask for the credentials again.

  Enter a value:
Error occurred: Otto uses your SSH Agent to authenticate with instances created in
AWS, but it could not verify that your SSH key is loaded into the agent.
The error message follows:

Error connecting to agent: dial unix C:/Users/John/AppData/Local/Temp/ssh-pBjh7WrXj8YE/agent.4940: socket: An address incompatible with the requested protocol was used.
bash-3.1$
```

**Comment by mitchellh** [comment]
This crash should be gone in Otto 0.1.2.

@johnyesberg The issue you're seeing is separate and has to do with SSH agent son Windows which we're tracking in another issue (sorry I can't find it right now but there aren't many). We're actively looking for a way to fix this.

**Comment by angelicalleite** [comment]
I download Otto 0.2 and have problem equals, double click in otto.exe and nothing, but when run for cmd ok, I try "install" but did not work, so  

1°: use cmd
2°: cd path dir executable otto.exe
3°: run otto.exe for cmd
4°: ok, return command of otto but not install

5°: I try test up path com cd .. and otto not work :(

I try for windows 64bits.
