### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by AndrewDryga** [hashicorp/otto#231]
Hi guys,

Can you, please, create a homebrew formula to install otto. It would be much easier to start using it, and simplify update process.

**Comment by fatroom** [comment]
There's already descriptor for otto in cask exists. Just do:

    brew install caskroom/cask/brew-cask
    brew cask install otto

And also there's open PR in home-brew for formula: Homebrew/homebrew#44469

**Comment by sethvargo** [comment]
Thanks @fatroom!
