### ISSUE TITLE
`otto dev ssh` exit status 255

### ISSUE THREAD

**Issue by premsompura** [hashicorp/otto#232]
I cloned the otto-getting-started repo into my machine and then ran the command as instructed in getting started guide:
```$ otto compile```
which compiled successfully
after that I changed ```config.vm.box="ubuntu/trusty64"```  in **VagrantFile** located in __*.otto/compiled/app/dev*__ because I used to work on vagrant machines so I already have a vagrant box.
and then,
 ```$ otto dev```
which gave the output **Development environment successfully created!** with few other basic info like ip address.
after that i ran the command to login which gave me output
>$ otto dev ssh
==> Executing SSH. This may take a few seconds...
exit status 255

**Comment by hoscb** [comment]
You have to start and run your virtualbox.

**Comment by premsompura** [comment]
virtualbox is already running

**Comment by evansvince** [comment]
Shut VirtualBox down. Make sure all boxes are shut down correctly.
In your vagrant file, change `config.vm.box` to be the name of the box you already have installed. Run `otto compile` then `otto dev` again. If that doesn't work, add `config.vm.box_url` to the vagrantfile. The URL should point to a local file where the box is. Run `otto compile` and `otto dev`.

You may have to delete the .vagrant and .otto files before you re-compile.

**Comment by pstephenwille** [comment]
Same here.  Starting from scratch on Ubuntu15, and VBox 5.

**Comment by justincampbell** [comment]
What's the output if you run `OTTO_LOG=1 otto dev ssh`?

**Comment by pstephenwille** [comment]
~/Projects/otto-getting-started$ OTTO_LOG=1 otto dev ssh
2015/10/14 10:36:17 [INFO] Otto version: 0.1.1  b4be6e9033ef2bf53ab2058ae956ef08125c7fa9+CHANGES
2015/10/14 10:36:17 [DEBUG] reading IP, cache path: /home/stephen/Projects/otto-getting-started/.otto/data/dev_ip
2015/10/14 10:36:17 [DEBUG] read ip from cache: 172.16.1.146
2015/10/14 10:36:17 Detected home directory from env var: /home/stephen
2015/10/14 10:36:17 [INFO] Loading app implementation for Tuple: ("ruby", "aws", "simple")
2015/10/14 10:36:17 [DEBUG] installIfNeeded: vagrant
2015/10/14 10:36:17 [DEBUG] installIfNeeded: vagrant installed: 1.7.4
2015/10/14 10:36:17 [DEBUG] installIfNeeded: vagrant latest: 1.7.4
2015/10/14 10:36:17 [DEBUG] installIfNeeded: vagrant min: 1.7.4
2015/10/14 10:36:17 [DEBUG] installIfNeeded: vagrant no installation needed
==> Executing SSH. This may take a few seconds...
exit status 255

**Comment by premsompura** [comment]
output of ```OTTO_LOG=1 otto dev ssh```

>2015/10/16 12:02:45 [INFO] Otto version: 0.1.1  b4be6e9033ef2bf53ab2058ae956ef08125c7fa9+CHANGES
2015/10/16 12:02:45 Detected home directory from env var: /home/prem
2015/10/16 12:02:45 [DEBUG] reading IP, cache path: /home/prem/sample-test/otto-sample-project/otto-getting-started/.otto/data/dev_ip
2015/10/16 12:02:45 [DEBUG] read ip from cache: 172.16.1.66
2015/10/16 12:02:45 [INFO] Loading app implementation for Tuple: ("ruby", "aws", "simple")
2015/10/16 12:02:45 [DEBUG] installIfNeeded: vagrant
2015/10/16 12:02:45 [DEBUG] installIfNeeded: vagrant installed: 1.7.4
2015/10/16 12:02:50 [DEBUG] installIfNeeded: vagrant latest: 1.7.4
2015/10/16 12:02:50 [DEBUG] installIfNeeded: vagrant min: 1.7.4
2015/10/16 12:02:50 [DEBUG] installIfNeeded: vagrant no installation needed
==> Executing SSH. This may take a few seconds...
ssh_exchange_identification: Connection closed by remote host
exit status 255

**Comment by dimianstudio** [comment]
The same issue on mac os x 10.11.1

Vagrantfile
```ruby  
config.vm.box = "ubuntu/trusty64"
```
output of OTTO_LOG=1 otto dev ssh
```shell                                                                                                                         
2015/10/31 11:45:44 [INFO] Otto version: 0.1.2  cc1a81fbce872ab1e2eff6342b8fa273cd9ebc0e
2015/10/31 11:45:44 Detected home directory from env var: /Users/dmst
2015/10/31 11:45:44 [DEBUG] reading IP, cache path: /Users/dmst/Work/Ruby/Streamline/.otto/data/dev_ip
2015/10/31 11:45:44 [DEBUG] read ip from cache: 172.16.1.152
2015/10/31 11:45:44 [INFO] Loading app implementation for Tuple: ("custom", "aws", "simple")
2015/10/31 11:45:44 [DEBUG] installIfNeeded: vagrant
2015/10/31 11:45:45 [DEBUG] installIfNeeded: vagrant installed: 1.7.4
2015/10/31 11:45:45 [DEBUG] installIfNeeded: vagrant latest: 1.7.4
2015/10/31 11:45:45 [DEBUG] installIfNeeded: vagrant min: 1.7.4
2015/10/31 11:45:45 [DEBUG] installIfNeeded: vagrant no installation needed
==> Executing SSH. This may take a few seconds...
ssh_exchange_identification: Connection closed by remote host
exit status 255
```

**Comment by AresDev** [comment]
The same issue on mac os x 10.11.1 doing the getting-started guide.

output of OTTO_LOG=1 otto dev ssh

2015/10/31 16:40:20 [INFO] Otto version: 0.1.2  cc1a81fbce872ab1e2eff6342b8fa273cd9ebc0e
2015/10/31 16:40:20 Detected home directory from env var: /Users/AresDev
2015/10/31 16:40:20 [DEBUG] reading IP, cache path: /Users/AresDev/Developer/Tests/otto/otto-getting-started/.otto/data/dev_ip
2015/10/31 16:40:20 [DEBUG] read ip from cache: 172.16.1.126
2015/10/31 16:40:20 [INFO] Loading app implementation for Tuple: ("ruby", "aws", "simple")
2015/10/31 16:40:20 [DEBUG] installIfNeeded: vagrant
2015/10/31 16:40:20 [DEBUG] installIfNeeded: vagrant installed: 1.7.4
2015/10/31 16:40:21 [DEBUG] installIfNeeded: vagrant latest: 1.7.4
2015/10/31 16:40:21 [DEBUG] installIfNeeded: vagrant min: 1.7.4
2015/10/31 16:40:21 [DEBUG] installIfNeeded: vagrant no installation needed
==> Executing SSH. This may take a few seconds...
/Users/AresDev/.otto.d/cache/f56bfa83-daa3-6b66-e2aa-a2eb21ce0e05/dev_ssh_cache: line 1: Bad configuration option: /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/pre-rubygems.rb:31:
/Users/AresDev/.otto.d/cache/f56bfa83-daa3-6b66-e2aa-a2eb21ce0e05/dev_ssh_cache: line 2: Bad configuration option: /opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/shared_helpers.rb:78:
/Users/AresDev/.otto.d/cache/f56bfa83-daa3-6b66-e2aa-a2eb21ce0e05/dev_ssh_cache: terminating, 2 bad configuration options
exit status 255

**Comment by jakedeichert** [comment]
I figured this out! I had this exact same problem when I used otto's auto-generated Vagrantfile with `ubuntu/trusty64` instead of `hashicorp/precise64`.

First, instead of manipulating `.otto/compiled/app/dev/Vagrantfile`, copy it to the same directory as your Appfile. Your Appfile should look like this:

~~~
application {
    name = "my-app"
    type = "custom"
}

customization "dev" {
    vagrantfile = "./Vagrantfile"
}
~~~

**Solution for SSH exit status 255**
In your Vagrantfile, these lines are probably within the auto-generated inline script section:
~~~bash
# Configuring SSH for faster login
if ! grep "UseDNS no" /etc/ssh/sshd_config >/dev/null; then
  echo "UseDNS no" | sudo tee -a /etc/ssh/sshd_config >/dev/null
  oe sudo service ssh restart
fi
~~~

Comment/remove the above lines and do:

~~~bash
otto dev destroy
otto compile
otto dev
...
otto dev ssh # And you're in!
~~~

**Comment by mitchellh** [comment]
This is fixed!
