### ISSUE TITLE
Azure driver for otto

### ISSUE THREAD

**Issue by TsuyoshiUshio** [hashicorp/otto#233]
I love HashiCorp products. Thank you for great products! I'd like to use otto on Azure. Is there any way to contribute or should I just wait for a while?

**Comment by mitchellh** [comment]
Here is the copy text I've been saying to all infra enhancements (below). We're certainly interested in Azure. :) If you want to contribute you may but please read the disclaimer below.

=======

Thanks! 

We're going to hold off for a version or two here on merging new infrastructures. We want to make sure we flesh out the abstractions necessary for upgrading infrastructures and so on over time. This might require core changes and we don't want to be on the hook for a bunch of different infra types yet.

I'm going to keep this PR open in the mean time and we'll come back to it then. Thanks again.

**Comment by ritazh** [comment]
Hi there! Looks like there have been lots of recent activities on terraform for Azure provider. Please let us know when it's a good time to work with vendors to get Otto working on Azure. We are happy to contribute!

**Comment by wmeints** [comment]
I hope azure makes it into otto very soon! I am using Azure for a lot of things and I love Otto, so I'd like to use the two together.
