### ISSUE TITLE
Error on BitBucket dependency

### ISSUE THREAD

**Issue by redbonesmith** [hashicorp/otto#236]
trying such appfile, repo is private, ssh is set up for it
```ruby
application {
  name = "test"
  type = "node"

  dependency { source = "bitbucket.org/redbonesmith/test.git" }
}
```
getting
>Error compiling Appfile: Error loading source: shorthand BitBucket URL can't be used for private repos, please use a full URL

**Comment by jmetzmeier** [comment]
Does bitbucket allow you to put and API key in the URL like github does?

**Comment by mrluc** [comment]
Does otto allow `git@bitbucket.org:user/repo` style sources?

**Comment by mitchellh** [comment]
@mrluc Yes, see the Generic Git Sources section here: https://ottoproject.io/docs/appfile/dep-sources.html
