### ISSUE TITLE
Otto Requires Dependency to Have Appfile

### ISSUE THREAD

**Issue by XedinUnknown** [hashicorp/otto#237]
Hi,

I have been reading the docs for a couple of days, and only now have had the chance to try it out. I want to use Otto to create an easily "uppable" testing environment for a range of WordPress plugins that I develop. Naturally, WordPress is a requirement. However, while I have failed to find this anywhere in the docs, it appears that Otto requires its dependencies to have Appfiles! Is this correct? When I run `otto compile` I get this:

```
$ otto compile
[0m[1m==> Loading Appfile...[0m
[0m[1m==> Fetching all Appfile dependencies...[0m
[0m    Fetching dependency: git::https://github.com/WordPress/WordPress.git[0m
[0;31mError compiling Appfile: Error parsing Appfile in git::https://github.com/WordPress/WordPress.git: open D:\Workshop\projects\wpra\test-environm
ent\.otto\appfile\deps\87c79aa2e6cf52cfd6ddbd08622c0120\Appfile: The system cannot find the file specified.[0m
```

Appfile
```
application {
    type = "php"
    name = "wpra-test-environment"

    dependency {
        source = "github.com/WordPress/WordPress.git"
    }
}
```

## Update ##

Subsequent runs result in the following output

```
$ otto compile
[0m[1m==> Loading Appfile...[0m
[0m[1m==> Fetching all Appfile dependencies...[0m
[0;31mError compiling Appfile: remove D:\Workshop\projects\wpra\test-environment\.otto\appfile\deps\87c79aa2e6cf52cfd6ddbd08622c0120\.git\objects\pac
k\pack-ca265d4bebe09a23365cadbd643c6ea14ddb7d5a.idx: Access is denied.[0m
```

**Comment by mitchellh** [comment]
Hm, it shouldn't _require_ this, it should be able to use Appfile defaults. I'll take a look at this.

Note that most dependencies will struggle without an Appfile most likely, though. But this still seems like a bug.

**Comment by XedinUnknown** [comment]
Hi,

And thanks for your prompt reply.

If what you say is true, then I anticipate many problems with dependencies that are common in the web-dev world. Especially for projects that already use Composer and such. Is there a plan to handle this somehow? For example, while I don't use Ruby, the docs mention that Otto will install Ruby's package manager. I assume it will also use it to install Ruby-type dependencies. Perhaps, Composer config files could be parsed into the directory and treated as dependencies, and then Composer in turn again could be used to install them?

A related question: what happens if I want a project that uses a specific engine depend on a module for that specific engine? In my example, I need the project to depend on WP, but also on a WP plugin.

Also, I am not seeing what I deduce are supposed to be `←` symbols. These are question marks in the pasted output. Locally I see them as squares. I used Git Bash under Win 10.

**Comment by mitchellh** [comment]
The Windows symbol issues are tracked in another issue and will be fixed. 

I don't see the issue with dependencies right now: they will automatically install Ruby/Composer dependencies. Deducing dependencies such as databases will also automatically be done.

**Comment by XedinUnknown** [comment]
So, if I need my WP app to depend on a WP plugin, should I create a Composer file? Or list it in the Appfile somehow? Sorry, very confused.

**Comment by XedinUnknown** [comment]
By the way, I do realize that the GH issue tracker is not the best support channel. But I haven't found anything else. Correct me if I'm wrong.
