### ISSUE TITLE
otto compile halt while compiling foundation consul

### ISSUE THREAD

**Issue by mbunge** [hashicorp/otto#240]
Otto halts on cpile step. Files will generated. Otto dev is halting to.

System:

- Windows 7 x64
- Vagrant 1.7.4
- VirtualBox 5.0.0
- 16 GB Ram, I5, with SSD

Appfile:
```hcl
application {
    name = "otto-php-example"
    type = "php"
}

customization "php" {
    php_version = "5.6"
}
```

Debug `otto compile`:
![ottobug](https://cloud.githubusercontent.com/assets/395518/10425578/fc2e85ec-70d8-11e5-8c36-b0f7f3311d61.jpg)

Debug `otto dev`
![ottobug2](https://cloud.githubusercontent.com/assets/395518/10425641/6e615e82-70d9-11e5-92fb-be604a028f42.jpg)

**Comment by johnyesberg** [comment]
Have a look at your network adapters. I had a similar problem. I found some virtualbox network adapters which had fixed ip addresses like the ones listed. I changed them to use automatically assigned addresses. Otto was then able to proceed past this point.

**Comment by mbunge** [comment]
Hi, Thank you for this advise. But we need fixed addresses at work.

**Comment by mitchellh** [comment]
This should be fixed in master.
