### ISSUE TITLE
Pluggable Dependency Analyzer

### ISSUE THREAD

**Issue by ramukima** [hashicorp/otto#243]
I have an application that allows modules to be loaded. The application defines a way for specifying module to module dependency. Say I have two module foo and bar. Each module runs using the same infrastructure. Each module has a defined structure that must be followed. Module bar depends on module foo and the metadata for such a dependency exists in bar/dependency.json that my application is capable of loading.

I understand that with Otto, I will need to have a bar/Appfile and a foo/Appfile. Now, can I have a plugin developed to analyze the module to module dependency based on dependency.json instead of mandating an Appfile on every module (avoid duplicating dependency.json in Appfile) ?

How customizable the Appfile dependency analyzer is ?

**Comment by mitchellh** [comment]
You can do this in Otto 0.2 with a custom app type plugin!
