### ISSUE TITLE
Incorrect IP

### ISSUE THREAD

**Issue by evansvince** [hashicorp/otto#246]
After I run `otto dev` I get:

<img width="601" alt="screen shot 2015-10-13 at 6 51 32 pm" src="https://cloud.githubusercontent.com/assets/10272935/10470537/e283b0d2-71db-11e5-8673-d9f725e768f4.png">.

The IP that is given does not work. The error says `This webpage is not available. ERR_CONNECTION_REFUSED`.

`otto status` is: 

<img width="316" alt="screen shot 2015-10-13 at 6 51 47 pm" src="https://cloud.githubusercontent.com/assets/10272935/10470562/20db6f82-71dc-11e5-8224-8948e9fce01d.png">

**Comment by chad-thompson** [comment]
I'll note here that at present the PHP module doesn't install a web server for most defaults.  (i.e. it's limited to starting the local PHP server - hence the :5000 port.  There's an NGINX install in the works.

**Comment by mitchellh** [comment]
@evansvince I tried a basic PHP example and the IP worked for me, you just have to make sure to access it at port 5000 as the instructions say. Let me know if things are different for you.
