### ISSUE TITLE
otto compile on a laravel app detected node

### ISSUE THREAD

**Issue by csrui** [hashicorp/otto#247]
Disclaimer: Total newb testing out otto for the first time here. 

Compiling on a Laravel app detected an app of type Node instead of PHP. The rest of the configuration is still uknown to me so nothing popups.

**Comment by justincampbell** [comment]
@csrui I believe this has been fixed (https://github.com/hashicorp/otto/pull/149), and will be available in the next release. Feel free to reopen if I'm mistaken. Thanks!

**Comment by justincampbell** [comment]
@csrui Also, in the meantime, creating an `Appfile` with these contents should work:

```hcl
application {
    type = "php"
}
```
