### ISSUE TITLE
Encrypted Credentials Password prompt can't be exited

### ISSUE THREAD

**Issue by sgoings** [hashicorp/otto#252]
It's not possible to Ctrl-C or Ctrl-D during the Encrypted Credentials Password prompt. The available workaround is to mistype the authentication password and press enter.

**Comment by justincampbell** [comment]
I've felt this pain too, thanks for reporting!

**Comment by mitchellh** [comment]
Fix is in a PR upstream here: https://github.com/hashicorp/vault/pull/705

Once that is merged, this will be fixed!
