### ISSUE TITLE
"Otto init" to generate an Appfile

### ISSUE THREAD

**Issue by jeyvison** [hashicorp/otto#264]
Hi guys.
I was wondering if otto could have something like an **"init**" command to generate the Appfile. I Know this file is optional but if you decide to create it, it would be good to have a "template file" to work on.

Actually, i'm working on this command on my forked repo.

What do you think about it as a feature?

**Comment by justincampbell** [comment]
Sounds good to me! Would it write the current defaults for the detected app, or would it just be a generic template?

**Comment by jeyvison** [comment]
At first, it could be just a template where the user could send a **-lang** flag to tell the command  what kind of language the project would use.  Later, we could modify it to get the defaults for the detected app?

PS: Sorry, if i wrote something wrong. My english is not that good ^^

**Comment by mitchellh** [comment]
This is actually dup of #172 although the title of this one is arguably better. :) Please watch that!
