### ISSUE TITLE
Change the documentroot

### ISSUE THREAD

**Issue by GuillaumeDievart** [hashicorp/otto#265]
Hi,

I test Otto on a PHP application, but I not find where I can modify the Apache documentRoot on build. I want, that the public directory is used as DocumentRoot.

my application structure:
.
├── app
├── Appfile
├── composer.json
├── composer.lock
├── .gitignore
├── .otto
├── .ottoid
├── public
├── tests
└── vendor

Thanks !

**Comment by GuillaumeDievart** [comment]
Already an issue open: https://github.com/hashicorp/otto/issues/164

**Comment by guycalledseven** [comment]
This dupe of #152 better conversation going on there
