### ISSUE TITLE
Go-bindata and Stringer file not found in $PATH

### ISSUE THREAD

**Issue by shubham90** [hashicorp/otto#266]
Following the documentation for the dev setup, after doing a 'make updatedeps', 'make' is crashing at go generate. The executables for dependencies is missing in the $PATH and thus the error. 

I suspect this to be a documentation bug which puts the dependencies into the $PATH.

OS: Fedora 21

Full Traceback: http://fpaste.org/280804/45204292/

**Comment by justincampbell** [comment]
@shubham90 What's the output of `go env`? Do you see `$GOBIN` in your `$PATH`?

```sh
echo $PATH | grep --color $GOBIN
```

**Comment by shubham90** [comment]
@justincampbell 
Ah.. I see. I didn't set up my $GOBIN in the $PATH. Thanks a lot for the response.
