### ISSUE TITLE
Stuck on build

### ISSUE THREAD

**Issue by blocka** [hashicorp/otto#273]
Otto seems to be stuck at this point
`==> otto: Uploading /tmp/otto-slug-722904841 => /tmp/otto-app.tgz`

This is a node app, being deployed to aws.

**Comment by justincampbell** [comment]
@blocka Could you please post the output of `OTTO_LOG=1 otto build`?

**Comment by blocka** [comment]
I know you don't want to here this, but I've temporarily given up on otto, so I don't have this set up anymore to reproduce. I think I may have gotten farther, but sort of gave up when I realized the narrowness of how the project had to be structured.

**Comment by mitchellh** [comment]
No problem. We'll try to reproduce it ourselves and if we run into it we'll fix it. Otto is still young and has a lot of growing to do, but we're fixing things up very quickly. :) Thanks for trying!
