### ISSUE TITLE
Custom php version on dev

### ISSUE THREAD

**Issue by ilyar** [hashicorp/otto#277]
### Info

* Install PHP 5.4 - ppa:ondrej/php5-oldstable
* Install PHP 5.5 - ppa:ondrej/php5
* Install PHP 5.6 - ppa:ondrej/php5-5.6

### Otto v0.1.2

`Appfile`
```HCL
customization "php" {
 // 1 php_version = "oldstable" // Install PHP 5.4
 // 2 php_version = "" // Install PHP 5.5
 // 3  php_version = "5.6" // default Install PHP 5.6
}
```

`.otto/compiled/app/dev/Vagrantfile`
```ruby
...
  1 OK - oe sudo add-apt-repository -y ppa:ondrej/php5-oldstable
  2 ERROR - oe sudo add-apt-repository -y ppa:ondrej/php5-
  3 OK oe sudo add-apt-repository -y ppa:ondrej/php5-5.6
...
```

### Proposal

`Appfile`
```HCL
customization "php" {
  ppa = "ppa:ondrej/php5-5.6" // Custom php version
}
```

`.otto/compiled/app/dev/Vagrantfile`
```ruby
...
  oe sudo add-apt-repository -y ppa:ondrej/php5-5.6
...
```

**Comment by chad-thompson** [comment]
Take a look at this pull request:

https://github.com/hashicorp/otto/pull/242

I attempted to write a script that could potentially be independent of creating a PPA - i.e only specify the version, do the PPA work (it does use the ondrej repos) behind the scenes.

**Comment by justincampbell** [comment]
I think ultimately we'd prefer to have users thinking about version numbers, and not the packages that install them. #242 is a pretty good step in that direction for customizing the PHP version. Going to close this for now, but after #242 maybe we can revisit if there's still something missing. Thanks!
