### ISSUE TITLE
Invalid vagrantMinVersion

### ISSUE THREAD

**Issue by jrslv** [hashicorp/otto#297]
I'm not sure why `vagrantMinVersion` was changed from `1.7.4` (currently latest vagrant) to `1.8.0` in f39190ea and then to `1.7.99` in 9e52549c, but it currently produces this error:

```
An older version of vagrant was found installed (1.7.4). Otto requires
version 1.7.99 or higher. Otto can install the latest version of vagrant
for you (1.7.4). Would you like Otto to update vagrant for you?
```

I guess `1.7.4` should be the `vagrantMinVersion` now.

**Comment by leowmjw** [comment]
I also encountered the same issue, I went ahead to just patch it back down to 1.7.4 for now and recompiled; seems fine so far.

I presume the 1.8.0 dependency will be needed by Otto 0.2 as it uses Vagrant's layer clone to speed up otto dev --> https://twitter.com/mitchellh/status/659414832450551809

**Comment by sethvargo** [comment]
Hi all,

This is intentional. There are things in Otto master that require the newest version of Vagrant (released mid this month).
