### ISSUE TITLE
Confusing error message 

### ISSUE THREAD

**Issue by themccallister** [hashicorp/otto#299]
I was trying to deploy a simple Lotus application to test with the following Appfile:

```
application {
    name = "lotus-example"
    type = "ruby"
}

project {
    name = "lotus-example"
    infrastructure = "aws"
}

infrastructure "production" {
    type = "aws"
    flavor = "simple"
}
```

Then when I went to `otto compile` I had a very interesting error message (see attached screenshot).

```
project: infra 'aws' has no corresponding infrastructure stanza
```

<img width="500" alt="screenshot 2015-11-05 18 43 16" src="https://cloud.githubusercontent.com/assets/5354908/10987998/4eb05422-83ed-11e5-9436-b50b90e92f54.png">

This was simple to fix as the project infrastructure value must be the correct name of the infrastructure (not "aws"), in this case it should have been "production".

I copied this straight from the code on the documentation and it does cover this configuration in the following paragraph on this page https://ottoproject.io/docs/appfile/project.html.

> infrastructure (string) - The name of the infrastructure that this project should be deployed onto by default. This should match the name of a configured infrastructure.

However, maybe the documentation should say something along these lines to reflect the code displayed above: 

> infrastructure (string) - The name of the infrastructure that this project should be deployed onto by default. This should match the name of a configured infrastructure. In this case the infrastructure is named "aws".

In the long run, the error message is rather confusing and the documentation could be a little more "together" with adding a complete `Appfile` to demonstrate the entire configuration option - even though we are discouraging config files for deployment.

**Comment by justincampbell** [comment]
Thanks! I updated the docs to have the same name ("production") in both places, and added some of your copy.
