### ISSUE TITLE
Dependencies (example mongoDB) does not get deployed to AWS

### ISSUE THREAD

**Issue by leowmjw** [hashicorp/otto#316]
Just using a simple PHP app with the example mongoDB inside Docker; Appfile as below:

```
basic-php leow$ cat Appfile 
application {
    name = "basic-otto-php"
    type = "php"

    dependency {
      source = "/Users/leow/OTTO/WORKSPACE/otto/examples/mongodb"
    }
}
```
It works fine and is deployed in "otto dev" but does not seem to be deployed in AWS.

I presume this is due to the source being a local file?  I would at least expect an error message when running "otto build" to remind user to have it.

**Comment by GuillaumeDievart** [comment]
See https://github.com/hashicorp/otto/issues/269

**Comment by leowmjw** [comment]
Thanks @GuillaumeDievart!

Based on my newbie reading of the code at github.com/hashicorp/otto/otto/core.go; does not seem to be implemented; even in the current HEAD. Is this something planned for v0.2 @mitchellh?

```
// Deploy supports subactions, which can be specified with action and args.
// Action can be "" to get the default deploy behavior.
func (c *Core) Deploy(action string, args []string) error {
...
        // TODO: Verify that upstream dependencies are deployed

        // We only use the root application for this task, upstream dependencies
        // don't have an effect on the build process.
...

        // Pass through the requested action
        rootCtx.Action = action
        rootCtx.ActionArgs = args

        return rootApp.Deploy(rootCtx)
}
```

**Comment by SebastianSzturo** [comment]
Full production deployment support will come with v0.3 (probably before the end of 2016). 
As mentioned on [the episodes about otto on the changelog podcast](https://overcast.fm/+I_qNzu_g/1:10:38).

**Comment by GuillaumeDievart** [comment]
@SebastianSzturo Thx for the link !

**Comment by leowmjw** [comment]
@SebastianSzturo Thanks! Listened to it; it is actually end of 2015, maybe early Jan 2016 :)

**Comment by SebastianSzturo** [comment]
Sorry it was, of course, end of 2015. I forgot what year it is now :sweat_smile:
