### ISSUE TITLE
Customize Ruby Version Customisation Fails

### ISSUE THREAD

**Issue by beffa** [hashicorp/otto#318]
I have a Rails application with running with Ruby 2.0.0p643. In the Gemfile I specify `ruby '2.0.0'` 

1. Otto doesn't auto-configure the Ruby Version

2.  If I create a simple Appfile

```
application {
    name = "xyz"
    type = "rails"
}
customization "ruby" {
    ruby_version = "2.0.0p643"
}
```

or 

```
application {
    name = "xyz"
    type = "rails"
}
customization "ruby" {
    ruby_version = "2.0.0"
}
```

it configures ruby 1.87.

```
otto dev ssh 
ruby --version
ruby 1.8.7 (2012-02-08 patchlevel 358) [x86_64-linux
]
```

**Comment by saturnflyer** [comment]
I encountered the same problem today using `ruby_version = '2.2.2'`

**Comment by mitchellh** [comment]
This should be all fixed in master, since we switched to ruby-install, will be part of Otto 0.2

**Comment by saturnflyer** [comment]
thanks @mitchellh! as a brand spanking new user of otto, how can I use master? Would I need to get into the development instructions here https://github.com/hashicorp/otto#developing-otto and build locally?

**Comment by mitchellh** [comment]
That's right, though at this moment I wouldn't recommend it. It'll require Vagrant 1.8 which isn't out yet (we're working on it now!)
