### ISSUE TITLE
support for python apps

### ISSUE THREAD

**Issue by tony-garcia** [hashicorp/otto#319]
playing with Otto for the first time and ran otto compile in my python app. It wasn't recognized even though there was a setup.py and wsgi.py file in the root so I set up an Appfile with type="python". When I ran otto compile again I got this error:

* Error loading App implementation for 'python-test-app': app implementation for tuple not found: ("python", "aws", "simple")

So I'm assuming python app support is coming?

**Comment by jmetzmeier** [comment]
I had been working on python app support here: https://github.com/hashicorp/otto/pull/147

However, the code base has changed since I first opened the pull request, so the code needs to be altered in the same way the code of the other apps were changed. I hope to have it ready to merge this week.

**Comment by tony-garcia** [comment]
Great thanks! Will be following the progress on this.
