### ISSUE TITLE
First use with VMware provider errors out with otto dev

### ISSUE THREAD

**Issue by VMTrooper** [hashicorp/otto#325]
Hello Team,

This one is minor, but I wanted you to be aware. When I ran the tutorial and did my first "otto dev", otto told Vagrant to download the precise64 hashicorp box for vmware. After it finished downloading, I saw the output displayed below.

I RESOLVED my issue by doing a vagrant init with the box name, vagrant up, vagrant destroy, then otto dev again.  I'm not sure why the first boot reported an error.

FYI, here is the output:

==> default: Checking if box 'hashicorp/precise64' is up to date...
==> default: Verifying vmnet devices are healthy...
Vagrant failed to start the VMware network interfaces! The output
of the failed command, if any, is below. The usual cause for this
is invalid configuration of the VMware network components. If
the problem persists, please contact support.

Failed to start DHCP service on vmnet8
Failed to start some/all services

Error building dev environment: Error executing Vagrant: exit status 1

The error messages from Vagrant are usually very informative.
Please read it carefully and fix any issues it mentions. If
the message isn't clear, please report this to the Otto project.

**Comment by mitchellh** [comment]
This is usually an ephemeral issue. I wish it were easier to fix but VMware devices are really finicky. Otto underneath the covers here is just executing `vagrant up` the same way you did so it really is emphemeral. You sometimes just have to wait maybe 10 seconds for VMware to clean up network devices before trying again. Sorry for the weirdness, I wish VMware desktop products gave me a cleaner network API!
