### ISSUE TITLE
Provide better message when operation times out

### ISSUE THREAD

**Issue by saturnflyer** [hashicorp/otto#328]
On a new OS X machine I'm trying out otto and it seems like my connection dropped during the download of vagrant.

I saw this:
```
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Recv failure: Operation timed out

Error building dev environment: Error executing Vagrant: exit status 1

The error messages from Vagrant are usually very informative.
Please read it carefully and fix any issues it mentions. If
the message isn't clear, please report this to the Otto project.
```

I solved it by just rerunning `otto dev` but others might not be so bold and try again themselves. My initial reaction was frustration because the error isn't that informative: "Please fix this error" and "exit status 1" don't tell me what to do.
It would be helpful to add some message like "It looks like your internet connection may have dropped. Try running the same command again when your connection returns."

I'm sorry if this should instead have been reported at Vagrant.

**Comment by justincampbell** [comment]
Maybe we could suggest in Otto that the user try to run the command again.

Detecting a network issue/expanding the help message will have to be done in Vagrant.

**Comment by mitchellh** [comment]
This error is actually coming from Vagrant itself. Can you please report it there?

Thanks!
