### ISSUE TITLE
Postgres & Postgis

### ISSUE THREAD

**Issue by rehatkathuria** [hashicorp/otto#337]
Using the Postgis extension on Postgres causes the `otto dev` command to fail.

https://gist.github.com/rehatkathuria/e7e3ac2f41d8b4a56238

It looks like the migration fails because Postgres doesn't have the Postgis extension detected. Is this an issue or am I overlooking something super simple?

**Comment by justincampbell** [comment]
@rehatkathuria Do any of your migrations enable the extension? If it was manually enabled on your system and is now only reflected in `db/schema.rb`, the migrations won't run on a fresh database.

```
git grep enable_extension db/migrate
```

**Comment by rehatkathuria** [comment]
Ah, I haven't created any migrations that install or enable the extension. I'll have a gander through the internet and try to figure out how to do so. Thanks Justin!
