### ISSUE TITLE
Deployment of custom application

### ISSUE THREAD

**Issue by suyash1983** [hashicorp/otto#341]
I have one ESXi server containing multiple virtual machines. So with respect to that I have certain questions related to ``otto`` which is not clearly mentioned in the [Getting Started Guide](https://ottoproject.io/intro/):

- How do I deploy custom application/package on these virtual machines.
- If this application depends on certain packages then how can I mention dependencies in the [Appfile](https://ottoproject.io/docs/concepts/appfile.html). (For e.g. a custom application which requires Apache Tomcat, MySQL server, Memcached and some other packages)
- If this custom application requires set of scripts (to start the application with certain parameters and checks) to deploy on certain location(s) of target machine then where I have to put this information in the Appfile.
- How can I compile AMI images of that custom application for a specific Linux/kernel version.
- Do I need to install ``otto`` binary on ESXi

**Comment by justincampbell** [comment]
> How do I deploy custom application/package on these virtual machines.

Otto is currently only targeting AWS, but we would like to add support for many more infrastructure providers in the future. Underneath, Otto uses Terraform, which currently supports VMware vSphere: https://terraform.io/docs/providers/vsphere/index.html

> If this application depends on certain packages then how can I mention dependencies in the Appfile. (For e.g. a custom application which requires Apache Tomcat, MySQL server, Memcached and some other packages)

Dependencies are specified in the Appfile in an `application` block. Please see the Dependencies documentation here: https://ottoproject.io/docs/concepts/deps.html

> If this custom application requires set of scripts (to start the application with certain parameters and checks) to deploy on certain location(s) of target machine then where I have to put this information in the Appfile.

Otto tries to support best practices for the most common languages and frameworks. If the scripts and checks are typically configurable for this type of application, then we'd welcome a pull request adding it to the apptype.

> How can I compile AMI images of that custom application for a specific Linux/kernel version.

Packer will be used by Otto to compile the machine images. Otto targets best practices for common languages and frameworks, including the underlying operating system and kernel version, so this is not currently customizable.

> Do I need to install otto binary on ESXi

No, Otto will use Terraform to create and manage the VMs locally, without being installed on the infrastructure provider. However, Otto does not yet support ESXi or vSphere directly.

Hope this helps. Feel free to reopen if you have more questions. It would be helpful to know more about the application and language/framework you're using. Thanks!
