### ISSUE TITLE
dev_ssh_cache polluted

### ISSUE THREAD

**Issue by johnm** [hashicorp/otto#343]
Environment:  OSX 10.10.5, VirtualBox Version 5.0.10 r10406, 
Ran into this problem with all projects I try to use otto for on this machine. I've recreated the problem with the otto getting started sample setup...

'otto compile' works fine.

'otto dev' completes without error

'otto dev ssh' (with verbose logging) fails with exit status 255:
> ...
> ==> Executing SSH. This may take a few seconds...
> /Users/i850377/.otto.d/cache/80044293-8a75-deb5-3ea1-5f6d77e3f08c/dev_ssh_cache: line 1: Bad configuration option: /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/pre-rubygems.rb:31: /Users/i850377/.otto.d/cache/80044293-8a75-deb5-3ea1-5f6d77e3f08c/dev_ssh_cache: line 2: Bad configuration option: /opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/shared_helpers.rb:78:
> /Users/i850377/.otto.d/cache/80044293-8a75-deb5-3ea1-5f6d77e3f08c/dev_ssh_cache: terminating, 2 bad configuration options
> exit status 255

Looking at that dev_ssh_cache file, I find:
> /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/pre-rubygems.rb:31: w\
arning: Insecure world writable dir /opt in PATH, mode 040777
> /opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/shared_helpers.rb:78\
: warning: Insecure world writable dir /opt in PATH, mode 040777
> Host default
> ...

at the top of the file.

Going back through the 'otto dev' output (with verbose logging), I find:
> ...
> 2015/11/26 10:13:40 [DEBUG] exec: /usr/local/bin/vagrant up /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/pre-rubygems.rb:31: warning: Insecure world writable dir /opt in PATH, mode 040777
> /opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /opt in PATH, mode 040777
> ...

So, it looks like otto is oversharing some of the underlying tooling output and dumping that into the cache erroneously. 

This is related to: https://github.com/mitchellh/vagrant/issues/2185
but the fact that this is bubbling up through (to) otto adds another layer of confusion and annoyance to the problem and should really be fixed one way or another by the tooling. It's a generic problem of oversharing.

Alas, there are some cases where just doing the simple chmod fix doesn't work so great (like corporate owned machines with their own weird security crapware running :-). But even worse, in this case, just fixing the first one doesn't solve it since there are other cases where vagrant bubbles up this stuff and so the problem ends up being a game of wackamole and that is defeating the purpose of having higher-level tooling...
> 2015/11/26 10:39:08 [DEBUG] exec: /usr/local/bin/vagrant up
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/pre-rubygems.rb:31: warning: Insecure world writable dir /usr/local/instantclient_10_2 in PATH, mode 040777
> /opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /usr/local/instantclient_10_2 in PATH, mode 040777
:-(

So for e.g. vagrant, why not just add a 'silent' mode or somesuch that just outputs the core data that it should be dumping out for "machine consumption" without any extraneous blather?  Or make it dump the warnings/errors to stderr and core data out to stdout?

But in general, otto itself needs some more robust strategy for dealing with the output of the various underlying tooling that it relies on.

**Comment by mitchellh** [comment]
Ah this is a good bug. Those errors should come out on stderr so we should just capture stdout and use that.
