### ISSUE TITLE
import ".." {} not working

### ISSUE THREAD

**Issue by Morriz** [hashicorp/otto#346]
Hi, I am trying to setup a project with multiple apps like this:

api/Appfile
web/Appfile
lb/Appfile
Appfile

with the app Appfiles containing import ".." {} on top.
But when I compile them I see they don't pick up the import and end up creating blocks based on defaults.

I only have a project and infrastructure block in the root Appfile.
Also, I am using otto version 0.1.2

Hope someone can help me out :)

**Comment by leowmjw** [comment]
@Morriz Did you check out the section "Double-Slash to Split the Root and Subdirectory" at https://ottoproject.io/docs/appfile/dep-sources.html?  It seems similar to what you are facing.

```
If you specify the dependency like below, then Otto will be unable to get the next level dependency "../parent" because it won't exist since Otto only copies the root of the path given.
```

**Comment by justincampbell** [comment]
I believe @leowmjw is correct. Feel free to reopen if that doesn't work. Thanks!

**Comment by Morriz** [comment]
I didn't yet. I am sick :|
