### ISSUE TITLE
upstart.conf was removed after "otto dev"

### ISSUE THREAD

**Issue by muziyoshiz** [hashicorp/otto#352]
With no manual Appfile, "otto compile" creates &lt;app folder&gt;/.otto/compiled/app/foundation-consul/app-dev/upstart.conf file.

"otto dev" moves this upstart.conf to /etc/init/consul.conf. So if I execute "otto dev destroy" and "otto dev" again, the second "otto dev" failed to set up Consul.

In &lt;app folder&gt;/.otto/compiled/app/foundation-consul/app-dev/main.sh, following command is executed.

```
    # Setup Consul service and start it
    oe sudo mv ${dir}/upstart.conf /etc/init/consul.conf
```

I think this "mv" should be changed to "cp" as follows.

```
    # Setup Consul service and start it
    oe sudo cp ${dir}/upstart.conf /etc/init/consul.conf
```

**Comment by mitchellh** [comment]
Fixed by #354
