### ISSUE TITLE
Just deploy dependencies and not a specific app

### ISSUE THREAD

**Issue by jason-riddle** [hashicorp/otto#364]
I wish the following existed in otto, where given an example <code>Appfile</code>

```hcl
application {
    name = "spinnaker"

    dependency {
        source = "./clouddriver"
    }

    dependency {
        source = "./echo"
    }

    dependency {
        source = "./front50"
    }

    dependency {
        source = "./frontend"
    }

    dependency {
        source = "./gate"
    }

    dependency {
        source = "./igor"
    }

    dependency {
        source = "./orca"
    }

    dependency {
        source = "./redis"
    }

    dependency {
        source = "./rosco"
    }

    dependency {
        source = "./rush"
    }
}
```

The application is just deploying other dependencies and that's it. As of today, the <code>spinnaker</code> example application has to deploy some type of app (go, docker, etc.).

**Comment by justincampbell** [comment]
Do your deployed services form a tree? Wouldn't the "frontend" app be a starting point for a user, and therefore be the root of the dependency tree?

**Comment by jason-riddle** [comment]
Not 100% sure if they form a tree, because this is just something I created for the spinnaker project (https://github.com/spinnaker).  Let's pretend that they didn't form a tree and I wanted to test certain services by commenting them out from otto, regardless of it being frontend or something else. Does otto fit this use case or should I be looking at another tool?
