### ISSUE TITLE
Vagrant image responds 404

### ISSUE THREAD

**Issue by sampsakuronen** [hashicorp/otto#388]
Vagrant 1.8.1 is not found. It can still be easily installed with `brew cask install vagrant`.

    ➜  backend git:(master) ✗ otto dev
    Would you like Otto to install Vagrant?
      Otto requires vagrant to be installed, but it couldn't be found on your
      system. Otto can install the latest version of vagrant for you. vagrant
      will be installed system-wide since it uses system-specific installers.
      Would you like Otto to install vagrant for you? Alternatively, you may install
      this on your own.

      If you answer yes, Otto will install vagrant version 1.8.1.

      Please enter 'yes' to continue. Any other value will exit.

      Enter a value: yes

    ==> Downloading Vagrant v1.8.1...
        URL: https://dl.bintray.com/mitchellh/vagrant/vagrant_1.8.1.dmg

    Error building dev environment: Error downloading, status code 404

**Comment by mitchellh** [comment]
This is fixed, 0.2 will come out this week!
