### ISSUE TITLE
Additionally, the created environment must be started with a provider matching this provider. For example, if you're using VirtualBox, the clone environment must also be using VirtualBox.

### ISSUE THREAD

**Issue by shoneslab** [hashicorp/otto#420]
The command otto dev exits with error. My Machine is installed with Vmware fusion and the vagrant fusion plugin and virtual box.

How to make sure that otto uses either vmware fusion or virtualbox completely. The following logs starts with bringing machines with fusion but in the last layer it tries to bring the virtual box.

These are the logs:

==> Creating development environment layers...
..
==> Creating layer: consul
Bringing machine 'default' up with 'vmware_fusion' provider...
.....
==> Creating layer: ruby2.2
Bringing machine 'default' up with 'vmware_fusion' provider...
.....
==> Creating local development environment with Vagrant if it doesn't exist...
Bringing machine 'default' up with 'virtualbox' provider...
The clone environment hasn't been created yet. To clone from
another Vagrantfile, it must already be created with `vagrant up`.
It doesn't need to be running.

Additionally, the created environment must be started with a provider
matching this provider. For example, if you're using VirtualBox,
the clone environment must also be using VirtualBox.
Error building dev environment: Error executing Vagrant: exit status 1

The error messages from Vagrant are usually very informative.
Please read it carefully and fix any issues it mentions. If
the message isn't clear, please report this to the Otto project.

Thanks

**Comment by jgwhite** [comment]
You should be able to force the provider with the `VAGRANT_DEFAULT_PROVIDER` environment variable.

```
$ VAGRANT_DEFAULT_PROVIDER=vmware_fusion otto dev
```

**Comment by shoneslab** [comment]
Thanks so much. its resolved now
