### ISSUE TITLE
How to remove downed nodes

### ISSUE THREAD

**Issue by funkytaco** [hashicorp/otto#446]
I tried to remove my "laptop" node via a DELETE call to
http://host:4646/v1/node/51d312f9-85b1-7de0-68fe-357904115797

but I get "invalid method".

As you can see below, my laptop is showing up twice in the nodes list.

ID                                    DC   Name      Class   Drain  Status
d603b17b-261c-3679-5d74-e3aa35ea2ca4  dc1  app1     prod    false  ready
3b38ea74-c38b-56a2-affb-3788164fd2e7  dc1  app2     prod    false  ready
8505a423-5a2a-45ca-7a66-1feec9a52e7c  dc1  laptop   <none>  false  down
51d312f9-85b1-7de0-68fe-357904115797  dc1  laptop   <none>  false  down

**Comment by leowmjw** [comment]
@funkytaco You probably meant to post to the nomad issues; not in the otto channel?

**Comment by funkytaco** [comment]
Oops.
