### ISSUE TITLE
Error building dev environment on windows 10

### ISSUE THREAD

**Issue by AminulBD** [hashicorp/otto#465]
Hello,

When I run this ````otto dev```` command then, I get this error.

![problem](https://cloud.githubusercontent.com/assets/5006546/13727625/97aaf416-e923-11e5-878d-9fcc670895b8.PNG)

I'm using latest version of vagrant and virtual box.

Thanks!

**Comment by leowmjw** [comment]
Windows support is broken in v0.2 :(

See https://github.com/hashicorp/otto/pull/394 for the fix that I see has been merged into master.

So wait for v0.3 :)

**Comment by AminulBD** [comment]
@leowmjw hmm, I see and I'm waiting...
