### ISSUE TITLE
Is the server running locally and accepting connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

### ISSUE THREAD

**Issue by jbhatab** [hashicorp/otto#468]
I'm not sure if this is just something stupid I'm doing but I'm getting this error after setting up the default otto dev environment and trying to run 'rake db:create db:migrate db:seed'. It's definitely a config issue but I wanted to post this up because this took away from the 'magic' experience. Here's the console output.

![screen shot 2016-03-15 at 7 06 26 pm](https://cloud.githubusercontent.com/assets/2458718/13798138/4109debe-eae1-11e5-9204-1151375c491d.png)

I'm using mac osx 10.11.3.

Side note: The error I got when running otto compile when I didn't have virtual box installed was very unclear as well. I knew I had to install that but this would have blocked me if I didn't know this.

second side note: 'installing' otto is fairly simple by just  placing the binary in the correct folder but this is pretty unclear for most new people. Maybe a screenshot or a more packaged experience for mac users that feels familiar may help. Not sure on this one.

Love what you guys are doing, keep it up :D.

**Comment by leowmjw** [comment]
@jbhatab Look at previous tickets #330, #393, #396 for reference on working **Rails/Postgres** configuration

You will have to recompile with PR #447 (or manually modify the compiled Vagrantfile as per the PR) though, at least until it gets checked by Hashicorp folks and merged.

**Comment by jbhatab** [comment]
@leowmjw ok great. I'll look into this stuff. But at some point this should be clear in the whole process because the whole appeal of Otto is it's magic and postgres errors aren't magic. I actually stuck with heroku and set up my server on that because of this. Just wanted to give you some raw feedback :D
