### ISSUE TITLE
Creating layer: consul Error building dev environment layers: Error executing Vagrant: exit status 1

### ISSUE THREAD

**Issue by hogihung** [hashicorp/otto#478]
Hi,  I just installed otto and was following the getting started guide.  When I execute otto dev, I get the following error:

```
➜  otto-getting-started git:(master) ✗ otto dev
==> Creating development environment layers...
    Otto uses layers to speed up building development environments.
    Each layer only needs to be built once. We've detected that the
    layers below aren't created yet. These will be built this time.
    Future development envirionments will use the cached versions
    to be much, much faster.
==> Creating layer: consul
Error building dev environment: Error building dev environment layers: Error executing Vagrant: exit status 1

The error messages from Vagrant are usually very informative.
Please read it carefully and fix any issues it mentions. If
the message isn't clear, please report this to the Otto project.
➜  otto-getting-started git:(master) ✗
```

I checked and updated VirtualBox so now I am running version: 5.0.16 r105871.  I'm running on OSX Yosemite 10.10.5.

**Comment by leowmjw** [comment]
@hogihung Do check out #477; and collect the same logs and put it in gist if the solution there does not work for you.

It will be very curious if it shows the same symptoms; what were you doing with Vagrant right before encountering this issue?  If you have the actual commands used; that would be good too.

**Comment by hogihung** [comment]
Thank you for your response.  I looked at #477 and captured the output as requested.  You can see what steps I was following and the debug log at:  [error_gist](https://gist.github.com/hogihung/44dd8dd5792cfc7706aa89c162468e76)

**Comment by leowmjw** [comment]
@hogihung Looking at the gist; it is likely one of your currently installed vagrant plugin is causing the problem.

```
[INFO] ui raw: Vagrant failed to initialize at a very early stage:
```

It seems to be pretty common, see below cases for suggestions:
- https://github.com/mitchellh/vagrant/issues/5149
- https://github.com/mitchellh/vagrant/issues/6801
- https://github.com/mitchellh/vagrant/issues/6953

You can probably try updating or removing/reinstalling your vagrant plugins:
```
$ vagrant plugin update
```

The more drastic ones removed the entire ~/.vagrant.d or even re-installed Vagrant!

**Comment by hogihung** [comment]
Thank you!  The **vagrant plugin update** worked.  Guess I was focusing on the wrong error message.
