### ISSUE TITLE
otto dev fails when installing vagrant, with a non-helpful error message

### ISSUE THREAD

**Issue by piersb** [hashicorp/otto#484]
Specifically, the following:

Error building dev environment: exit status 1

Gist: https://gist.github.com/piersb/064b45f53c516144ec05d2544fda9c1b

**Comment by piersb** [comment]
I've had the following installed on my machine previously

- vagrant
- Virtualbox
- VMware fusion

I've attempted to uninstall everything, but it's possible I've missed a config file knocking around somewhere

**Comment by piersb** [comment]
10.11.4 (15E65), mid 2013 Macbook Air

**Comment by leowmjw** [comment]
@piersb Error logs shows permission problem.  You probably want to make sure you have the proper folders ready (e.g /usr/local/bin) when you install vagrant.

See for more details --> https://github.com/mitchellh/vagrant/issues/6034

**Comment by piersb** [comment]
Thanks. Looks like my recent update to 10.11.4 changed permissions and broke sudo. :(

Closing
