### ISSUE TITLE
Project's future

### ISSUE THREAD

**Issue by dmiskiew** [hashicorp/otto#495]
Hi,

I'm wondering what's the future of this project - github activity graph does not look very promising, and github issues are no longer labeled since Nov 2015.

Is hashicorp going to support / develop this tool? (I'm not complaining - just need to know what's the situation. If hashicorp made a decision, that community will take care of the issues that's ok)

**Comment by gotcha** [comment]
@dmiskiew Did you get any answer during those three days that lead you to close the issue ?
