### ISSUE TITLE
Getting Vagrant errors

### ISSUE THREAD

**Issue by Industrial** [hashicorp/otto#500]
==> Creating development environment layers...
    Otto uses layers to speed up building development environments.
    Each layer only needs to be built once. We've detected that the
    layers below aren't created yet. These will be built this time.
    Future development envirionments will use the cached versions
    to be much, much faster.
==> Creating layer: consul
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Cloning VM...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: consul_default_1461364372858_66518
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'poweroff' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

The primary issue for this error is that the provider you're using
is not properly configured. This is very rarely a Vagrant issue.
Error building dev environment: Error building dev environment layers: Error executing Vagrant: exit status 1

The error messages from Vagrant are usually very informative.
Please read it carefully and fix any issues it mentions. If
the message isn't clear, please report this to the Otto project.

**Comment by Industrial** [comment]
I'm not sure what error messages I should be seeing :-)

**Comment by leowmjw** [comment]
@Industrial I presume you are facing this error when running "otto dev".  

You should probably review #340 and try the suggestions mentioned there (as per below):
```
...
Ah, so the "entered an invalid state" is almost always (I've actually never seen it otherwise) a configuration issue with the underlying hypervisor. In this case, it looks like VirtualBox. The best way to debug this is to start VirtualBox manually (GUI) and manually click "Start" on the VM that Otto created. This should error and VirtualBox sometimes gives you better error messages in the UI.

A common scenario I've seen this is VT-x not enabled in the BIOS.
...
```

If above those not help; do mention your observations when manually starting the VM created by Otto.  

Please re-run but with maximum logging  as per below and upload as a gist:
```
$ otto dev destroy
$ VAGRANT_LOG=debug OTTO_LOG=1 otto dev
```
and paste the link to your gist here

**Comment by Industrial** [comment]
@leowmjw: https://gist.github.com/anonymous/9e33086383688220866108e31c3c66be

**Comment by Industrial** [comment]
I haven't used Vagrant before, but trying out otto I can't help but notice it says "Meet the new Vagrant" on the homepage. Howcome otto uses vagrant? I'm already pretty happy that I don't have to run a VM to run docker containers like on mac because I use Linux. Using Vagrant in the mix does mean I'll run everything from inside a VM in development mode, and otto will scale it out in production, right?

**Comment by leowmjw** [comment]
@Industrial yes; Otto uses Vagrant in the "dev" phase, in production it will be deployed (to a platform like AWS) using Terraform. Scaling and scheduling functionality will (in the future) likely be managed by Nomad.

Otto is meant to simplify the end-to-end App lifecycle (compile, dev, build, deploy) for a majority of Application Types through the use of Hashicorp's portfolio: Vagrant, Packer, Consul, Terraform and (future) integrations with Nomad, Vault.

BTW, did you try running the VM created manually via the GUI; any observed error message noticed (specifically "VT-x not enabled in the BIOS")?  I did a quick glance through the gist but did not see anything obvious from it.

**Comment by Industrial** [comment]
Yeah that's exactly the error I'm getting. Rebooting now to fix it :-)

**Comment by Industrial** [comment]
When I open up the VirtualBox GUI the one otto is managing isn't in the list. There is another one I tried with `vagrant init hashicorp/precise64` and `vagrant up` that didn't work either. When I unchecked and rechecked the VT-x checkbox it booted.

The error I'm getting now is

```
tom@Monster ~/Code/Code9/test-loopback                                                                                                                                                                                              [8:05:12] 
> $ otto compile                                                                                                                                                                                                        ⬡ 5.10.1 [±master ●▴]
==> Loading Appfile...
==> Fetching all Appfile dependencies...
==> Compiling...
    Application:    test-loopback (node)
    Project:        test-loopback
    Infrastructure: aws (simple)

    Compiling infra...
    Compiling foundation: consul
==> Compiling main application...
==> Compilation success!
    This means that Otto is now ready to start a development environment,
    deploy this application, build the supporting infrastructure, and
    more. See the help for more information.
    
    Supporting files to enable Otto to manage your application from
    development to deployment have been placed in the output directory.
    These files can be manually inspected to determine what Otto will do.
                                                                                                                                                                                                                                              
tom@Monster ~/Code/Code9/test-loopback                                                                                                                                                                                              [8:05:59] 
> $ otto dev                                                                                                                                                                                                           ⬡ 5.10.1 [±master ●●▴]
==> Creating development environment layers...
    Otto uses layers to speed up building development environments.
    Each layer only needs to be built once. We've detected that the
    layers below aren't created yet. These will be built this time.
    Future development envirionments will use the cached versions
    to be much, much faster.
==> Creating layer: consul
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Preparing master VM for linked clones...
    default: This is a one time operation. Once the master VM is prepared,
    default: it will be used as a base for linked clones, making the creation
    default: of new VMs take milliseconds on a modern system.
==> default: Cloning VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["clonevm", "a6ac14c8-488a-4418-94f6-f759bfdfd7dd", "--register", "--name", "temp_clone_1462017965939_32175"]

Stderr: VBoxManage: error: Could not find a registered machine with UUID {a6ac14c8-488a-4418-94f6-f759bfdfd7dd}
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(pszSrcName).raw(), srcMachine.asOutParam())" at line 431 of file VBoxManageMisc.cpp

Error building dev environment: Error building dev environment layers: Error executing Vagrant: exit status 1

The error messages from Vagrant are usually very informative.
Please read it carefully and fix any issues it mentions. If
the message isn't clear, please report this to the Otto project.
                                                                                                                                                                                                                                              
tom@Monster ~/Code/Code9/test-loopback                                                                                                                                                                                              [8:06:06] 
> $                                                                                                                                                                                                                    ⬡ 5.10.1 [±master ●●▴]
```

**Comment by Industrial** [comment]
It seems the problem was that symlinking ~/.vagrant.d doesn't work. I'll go check elsewhere to get that fixed :-)
