### ISSUE TITLE
Is project still active?

### ISSUE THREAD

**Issue by gnulnx** [hashicorp/otto#520]
I noticed that it has been several months since any code has changed in the repo and just wanted to inquire about the state of this project?   otto clearly works, but is work still ongoing?  is there still a 0.3 release planned?  Am I asking this question in the wrong place?  :)

**Comment by leowmjw** [comment]
@gnulnx Answer to your question:

https://groups.google.com/forum/#!topic/otto-tool/mscozaaRHG0
```
...
Otto is still under development, but we have limited resources and actively develop
over a dozen open source tools and several commercial products. Otto is more of a research
project currently and we iterate on it only when time allows. Hope that helps!

Best Regards,
Armon Dadgar
```

**Comment by gnulnx** [comment]
Thanks Armon, that actually does help a good bit.   I may continue to use it for a hobby project just to stay in the loop.
