### ISSUE TITLE
node app can't install 'bcrypt' or 'scrypt'

### ISSUE THREAD

**Issue by thewillhuang** [hashicorp/otto#521]
```bash
npm ERR! Linux 3.2.0-23-generic
npm ERR! argv "/opt/node-v6.2.2-linux-x64/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/npm-debug.log

```

https://github.com/barrysteyn/node-scrypt

and 

https://github.com/ncb000gt/node.bcrypt.js

both errors has to do with node-gyp

**Comment by ledsun** [comment]
I think this is a problem of the bcrypt.
The bcrypt may fail to build on Node v6.

Please refer to https://github.com/ncb000gt/node.bcrypt.js/issues/428

**Comment by thewillhuang** [comment]
let me close this one, i did a clean install of only bcrypt and scrypt and they both worked. The specific error i was running into was due to running out of memory

**Comment by sailaja-k** [comment]
While loading package npm-bcrypt@0.8.7:
   error: Command failed:
   C:\Users\sysh\AppData\Local\.meteor\packages\meteor-tool\1.4.0\mt-os.windows.
x86_32\dev_bundle\bin\npm.cmd
   rebuild --no-bin-links --update-binary
   gyp ERR! build error
   gyp ERR! stack Error:
   `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with
   exit code: 1
   gyp ERR! stack     at ChildProcess.onExit
   (C:\Users\sysh\AppData\Local\.meteor\packages\meteor-tool\1.4.0\mt-os.windows
.x86_32\dev_bundle\lib\node_modules\node-gyp\lib\build.js:276:23)
   gyp ERR! stack     at emitTwo (events.js:87:13)
   gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
   gyp ERR! stack     at Process.ChildProcess._handle.onexit
   (internal/child_process.js:200:12)
   gyp ERR! System Windows_NT 6.1.7601
   gyp ERR! command
   "C:\\Users\\sysh\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0\\mt-o
s.windows.x86_32\\dev_bundle\\bin\\node.exe"
   "C:\\Users\\sysh\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0\\mt-o
s.windows.x86_32\\dev_bundle\\lib\\node_modules\\node-gyp\\bin\\node-gyp.js"
   "rebuild"
   gyp ERR! cwd
   C:\Users\sysh\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\npm\node_module
s\.temp-1d1r34l\node_modules\bcrypt
   gyp ERR! node -v v4.4.7
   gyp ERR! node-gyp -v v3.4.0
   gyp ERR! not ok

   npm ERR! Windows_NT 6.1.7601
   npm ERR! argv
   "C:\\Users\\sysh\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0\\mt-o
s.windows.x86_32\\dev_bundle\\bin\\node.exe"
   "C:\\Users\\sysh\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0\\mt-o
s.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js"
   "rebuild" "--no-bin-links" "--update-binary"
   npm ERR! node v4.4.7
   npm ERR! npm  v3.10.5
   npm ERR! code ELIFECYCLE
   npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
   npm ERR! Exit status 1
   npm ERR!
   npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
   npm ERR! Make sure you have the latest version of node.js and npm
   installed.
   npm ERR! If you do, this is most likely a problem with the bcrypt
   package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node-gyp rebuild
   npm ERR! You can get information on how to open an issue for this
   project with:
   npm ERR!     npm bugs bcrypt
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls bcrypt
   npm ERR! There is likely additional logging output above.

   npm ERR! Please include the following file with any support request:
   npm ERR!
   C:\Users\sysh\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\npm\node_module
s\.temp-1d1r34l\npm-debug.log
   gyp ERR! build error
   gyp ERR! stack Error:
   `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with
   exit code: 1
   gyp ERR! stack     at ChildProcess.onExit
   (C:\Users\sysh\AppData\Local\.meteor\packages\meteor-tool\1.4.0\mt-os.windows
.x86_32\dev_bundle\lib\node_modules\node-gyp\lib\build.js:276:23)
   gyp ERR! stack     at emitTwo (events.js:87:13)
   gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
   gyp ERR! stack     at Process.ChildProcess._handle.onexit
   (internal/child_process.js:200:12)
   gyp ERR! System Windows_NT 6.1.7601
   gyp ERR! command
   "C:\\Users\\sysh\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0\\mt-o
s.windows.x86_32\\dev_bundle\\bin\\node.exe"
   "C:\\Users\\sysh\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0\\mt-o
s.windows.x86_32\\dev_bundle\\lib\\node_modules\\node-gyp\\bin\\node-gyp.js"
   "rebuild"
   gyp ERR! cwd
   C:\Users\sysh\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\npm\node_module
s\.temp-1d1r34l\node_modules\bcrypt
   gyp ERR! node -v v4.4.7
   gyp ERR! node-gyp -v v3.4.0
   gyp ERR! not ok

   npm ERR! Windows_NT 6.1.7601
   npm ERR! argv
   "C:\\Users\\sysh\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0\\mt-o
s.windows.x86_32\\dev_bundle\\bin\\node.exe"
   "C:\\Users\\sysh\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0\\mt-o
s.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js"
   "rebuild" "--no-bin-links" "--update-binary"
   npm ERR! node v4.4.7
   npm ERR! npm  v3.10.5
   npm ERR! code ELIFECYCLE
   npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
   npm ERR! Exit status 1
   npm ERR!
   npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
   npm ERR! Make sure you have the latest version of node.js and npm
   installed.
   npm ERR! If you do, this is most likely a problem with the bcrypt
   package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node-gyp rebuild
   npm ERR! You can get information on how to open an issue for this
   project with:
   npm ERR!     npm bugs bcrypt
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls bcrypt
   npm ERR! There is likely additional logging output above.

   npm ERR! Please include the following file with any support request:
   npm ERR!
   C:\Users\sysh\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\npm\node_module
s\.temp-1d1r34l\npm-debug.log


=> Your application has errors. Waiting for file change.


I am getting the above error when I tried to run meteor application. Can anyone help me with the solution to the above.

**Comment by nikhilshinde57** [comment]
I use this #http://stackoverflow.com/questions/29320201/error-installing-bcrypt-with-npm one.  It works same as bcrypt.
