### ISSUE TITLE
docker-external cannot give args to container

### ISSUE THREAD

**Issue by bigwheel** [hashicorp/otto#529]
I search same issue/pull req but didn't find it.

[docker run command can take args to container now](https://docs.docker.com/engine/reference/run/).
For example, [MySQL Official Image](https://hub.docker.com/_/mysql/) takes various options(see section "Configuration without a cnf file" in that page).
However, docker-external apps cannot treat it well.
run_args opiton is only give to "docker run" itself and no way to give container.

This is my example to try to give "--character-set-server" option.
```
 % otto dev destroy -f && otto dev
==> Destroying the local development environment...
==> default: Forcing shutdown of VM...
==> default: Destroying VM and associated drives...

==> Deleting development environment metadata...
==> Development environment has been destroyed!

・・・

==> default: Running provisioner: docker...
==> default: Starting Docker containers...
==> default: -- Container: mysql
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!


          rm -f /var/lib/vagrant/cids/f460c882a18c1304d88854e902e11b85d71e7e1b
          docker run --cidfile=/var/lib/vagrant/cids/f460c882a18c1304d88854e902e11b85d71e7e1b -d --name mysql --restart=always -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root --character-set-server=utf8mb4 mysql:5.7


Stdout from the command:



Stderr from the command:

stdin: is not a tty
flag provided but not defined: --character-set-server
See 'docker run --help'.

Error building dev environment: Error executing Vagrant: exit status 1

The error messages from Vagrant are usually very informative.
Please read it carefully and fix any issues it mentions. If
the message isn't clear, please report this to the Otto project.
otto dev  7.39s user 3.44s system 4% cpu 4:12.83 total
 %
```

I suggest to add new docker-external option "container_args" or simply "args".

**Comment by leowmjw** [comment]
@bigwheel As per https://github.com/mitchellh/vagrant/issues/7348, what you want to achieve is supported by Vagrant at the moment.

For now, you can modify the generated Vagrantfile found in .otto/compiled/app/dev/Vagrantfile; look for the section:
```
config.vm.provision "docker" do |d|
  d.run "mongodb", args: "-p 27017:27017", image: "mongo:3.0"
end
```

alter to:

```
config.vm.provision "docker" do |d|
  d.run "mongodb", args: "-p 27017:27017", image: "mongo:3.0", cmd: "--character-set-server=utf8mb4"
end
```

Then you can run "otto dev" and it should work.

**Comment by bigwheel** [comment]
Thank you fro reply.

> @bigwheel As per mitchellh/vagrant#7348, what you want to achieve is supported by Vagrant at the moment.
I will do this problem with the way you tell.
However, .otto directory should not be added in VCS, thus I have to do that modification in every develop environment.

Thereby, I think a way to support "docker run option" should be archived by expansion of docker-external app.

If I create pull request such expansion, Will it be accepted ?

**Comment by leowmjw** [comment]
@bigwheel Decision to accept PRs will be up to the Hashicorp folks; but do go ahead with the PR, all are welcomed :) At least people can compile their own with your solution; and once in a while I'll produce unofficial binaries as well incorporating popular PRs.

**Comment by bigwheel** [comment]
thank you for helpful advice.

I starts to create that PR now.
