### ISSUE TITLE
Website - Otto vs Custom Tools explanation is for Vault.

### ISSUE THREAD

**Issue by ferventcoder** [hashicorp/otto#64]
https://ottoproject.io/intro/vs/custom.html

**Comment by ferventcoder** [comment]
Looks like this is correct though: https://github.com/hashicorp/otto/blob/master/website/source/intro/vs/custom.html.md

**Comment by phinze** [comment]
Thanks! Fixed and should be deployed momentarily.

**Comment by ferventcoder** [comment]
I'll see you at PuppetConf next week? I should buy you a beer, love brew cask.

**Comment by ferventcoder** [comment]
Deleting that comment momentarily as it has nothing to do with this current issue. :)
