### ISSUE TITLE
Nomad website files are in this repo

### ISSUE THREAD

**Issue by st-isidore-de-seville** [hashicorp/otto#65]
Great announcement at Hashiconf!!!

In poking around the repo, I noticed references to Nomad website files in:
https://github.com/hashicorp/otto/tree/master/website

**Comment by phinze** [comment]
Thanks for the heads up! Should be fixed.

**Comment by st-isidore-de-seville** [comment]
you rock!!! you must be very busy following the keynote announcements @phinze :smile:
