### ISSUE TITLE
NPM not in path after otto compile

### ISSUE THREAD

**Issue by mootpt** [hashicorp/otto#67]
Seems NPM is not in the default path after compilation. Precise64 box, may just need `/usr/local/bin/` in the userpath.

**Comment by mootpt** [comment]
actually, scratch that: `/usr/local/bin` is in the path, but when I go to execute npm install it returns: `The program 'npm' is currently not installed.  You can install it by typing:
apt-get install npm`

**Comment by mootpt** [comment]
```
lrwxrwxrwx 1 root root       30 Sep 28 18:43 node -> /opt/node-v-linux-x64/bin/node
lrwxrwxrwx 1 root root       29 Sep 28 18:43 npm -> /opt/node-v-linux-x64/bin/npm
```

but `ls -l /opt/` returns:

```
vagrant_ruby/             VBoxGuestAdditions-4.2.0/ 
```

**Comment by mootpt** [comment]
```
tar -C /opt -xzf /home/vagrant/node.tar.gz 

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

Here is where the setup is failing.

**Comment by mootpt** [comment]
node.tar.gz is empty: `-rw-r--r-- 1 root    root       0 Sep 28 18:43 node.tar.gz`

**Comment by mootpt** [comment]
node_version is not set.

**Comment by mikebranski** [comment]
Yeah, node is not actually getting installed, though `otto compile && otto dev` doesn't indicate and errors.

**Comment by eddiezane** [comment]
Looks like it's referred to as `dev_node_version` [here](https://github.com/hashicorp/otto/blob/46ef5247c324bc4bab0e22b471da638343b2a444/builtin/app/node/customization.go#L13)

**Comment by phinze** [comment]
@eddiezane that was it - thank you!
