### ISSUE TITLE
AMI ami-7f6a1f1a not public

### ISSUE THREAD

**Issue by fromonesrc** [hashicorp/otto#68]
`otto infra` tries to bring up instances based on `ami-7f6a1f1a` but it does not seem to be public.

```
Error applying plan:

1 error(s) occurred:

* aws_instance.consul: Error launching source instance: AuthFailure: Not authorized for images: [ami-7f6a1f1a]
	status code: 400, request id: []
```

**Comment by chrisbaldauf** [comment]
+1, I saw this same issue.

**Comment by phinze** [comment]
On it!

**Comment by phinze** [comment]
Okay should be public now - sorry about that!

**Comment by chrisbaldauf** [comment]
Confirmed that I'm not getting that error any longer and have successfully completed `otto infra`. Thanks!
