### ISSUE TITLE
'otto dev ssh' fails

### ISSUE THREAD

**Issue by sjfloat** [hashicorp/otto#69]
====

%otto dev ssh
==> Executing SSH. This may take a few seconds...
VM must be created before running this command. Run `vagrant up` first.

Error executing Vagrant: exit status 1

The error messages from Vagrant are usually very informative.
Please read it carefully and fix any issues it mentions. If
the message isn't clear, please report this to the Otto project.

====

**Comment by sjfloat** [comment]
Running vagrant directly as advised fails since there is no Vagrantfile in the directory. There is one under the .otto directory:

    ./.otto/compiled/app/dev/Vagrantfile

OS X 10.9.5
Vagrant 1.7.4
Otto v0.1.0

**Comment by sjfloat** [comment]
User error: I skipped the 'otto dev' step!.

**Comment by divan** [comment]
Hit the same issue, actually, straight from the docs. After reading docs, somehow I decided that `otto compile` and `otto dev ssh` should be enough and all `otto dev` stuff will execute upon first `otto dev ssh`.
Probably, need to be more stressed in docs somehow.

**Comment by divan** [comment]
Just realized, that misleading and confusing part was in error message ("Run vagrant up first"). User knows he doesn't have to work with vagrant directly, so the message is confusing. I guess if error message was something like "You need to run `otto dev` first" - it would be quick and easy to understand own mistake.

**Comment by robkinyon** [comment]
Or maybe `otto dev ssh` should detect the lack of a dev setup (maybe by checking `otto status`?) and automagically run `otto dev` first.

**Comment by mitchellh** [comment]
Fixed
