### ISSUE TITLE
Malformed version: 1.7.4/lib/vagrant/pre-rubygems.rb:31:

### ISSUE THREAD

**Issue by houshuang** [hashicorp/otto#70]
Tried to install on a almost clean OSX 10.10.5. Used brew cask to install Virtualbox, otto tried pulling in vagrant but it seemed to fail, so I used brew cask to pull in vagrant (this might have left me with a half-broken version somewhere). Trying `otto dev` on the `otto-getting-started` dir gives me 

`Malformed version: 1.7.4/lib/vagrant/pre-rubygems.rb:31:`

Running vagrant by itself spits out the usual help text - doesn't seem broken.

**Comment by phinze** [comment]
Thanks for the report - that's definitely weird. Can you move `~/.otto.d` out of the way and see if that takes care of the error?

**Comment by phiroict** [comment]
Same issue here with an already installed version of Vagrant (1.7.4) on Archlinux 
(4.2.1-1-ARCH #1 SMP PREEMPT Tue Sep 22 06:57:07 CEST 2015 x86_64 GNU/Linux) 
otto version v0.1.0 Got the error on the first run of otto dev
The code seems to fail on the line : 
Kernel.exec("ruby", ENV["VAGRANT_EXECUTABLE"], *ARGV) in pre-rubygems.rb:31
the envronment value  VAGRANT_EXECUTABLE is not set. 
When I set this value to the vagrant executable : 
export VAGRANT_EXECUTABLE=$(which vagrant)
I get the same error. 
Also vagrant itself seems to work fine. I  have not tried downgrading vagrant as I am actively using it, but I may try it in a vm later.

**Comment by houshuang** [comment]
There is no .otto.d, only an .otto and an .ottoid. I tried several times to
delete the .otto directory, and rerunning otto compile.

On Mon, Sep 28, 2015 at 8:39 PM, Philip Rodrigues <notifications@github.com>
wrote:

> Same issue here with an already installed version of Vagrant (1.7.4) on
> Archlinux
> (4.2.1-1-ARCH #1 <https://github.com/hashicorp/otto/pull/1> SMP PREEMPT
> Tue Sep 22 06:57:07 CEST 2015 x86_64 GNU/Linux)
> otto version v0.1.0 Got the error on the first run of otto dev
> The code seems to fail on the line :
> Kernel.exec("ruby", ENV["VAGRANT_EXECUTABLE"], *ARGV) in pre-rubygems.rb:31
> the envronment value VAGRANT_EXECUTABLE is not set.
> When I set this value to the vagrant executable :
> export VAGRANT_EXECUTABLE=$(which vagrant)
> I get the same error.
> Also vagrant itself seems to work fine. I have not tried downgrading
> vagrant as I am actively using it, but I may try it in a vm later.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashicorp/otto/issues/70#issuecomment-143911559>.
>



-- 
http://reganmian.net/blog -- Random Stuff that Matters

**Comment by lslucas** [comment]
Same problem with me, I'am also in mac environment but have not use brew to install vagrant nor virtualbox, just downloaded and installed the last available binary.

My ruby version is 2.0.0p48.
Anything I need to install or upgrade to solve or help find a solution?

**Comment by lslucas** [comment]
I think I found a solution:

When using the command bellow always the same error occurs:
`$ otto dev
Error building dev environment: Malformed version: 1.7.4/lib/vagrant/pre-rubygems.rb:31:
`
So I use `$ vagrant --version` and a similar, but more complete error was shown:
`vagrant --version
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/pre-rubygems.rb:31: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777
Vagrant 1.7.4`

To fix, I used:
`sudo chmod go-w /usr/local/bin`

But, then again, a similar errors appered, the difference was the dir changed, was `/usr/local`, then `/usr/local/bit/bin`, then finaly `/usr/local/git`

**Comment by houshuang** [comment]
Can confirm that this works. Suggested fix: Either make otto ignore this
warning from vagrant (I'm guessing there is some matching of the expected
output from a vagrant command which fails - vagrant should still work), or
let otto output a message about what exactly is wrong (need to make sure
directory x is not writeable by all). As most people will be using otto
from their personal laptops, I think this is a silly issue to complain
about (I realize it comes from the Ruby binary itself).

Thanks a lot, Lucas!

**Comment by lslucas** [comment]
Good to know that it helped @houshuang 
I think thats it @phinze thanks for the project and keep good things like that coming.

**Comment by dimianstudio** [comment]
@lslucas great it works!

**Comment by MathieuDoyon** [comment]
thanks! work for me

**Comment by csrui** [comment]
I'm getting otto from the download's page and I'm still getting this error. Currently using Mac OS 64 download.
