### ISSUE TITLE
'otto help dev' does not work as expected

### ISSUE THREAD

**Issue by winks** [hashicorp/otto#74]
I just had to dig [in the source](https://github.com/hashicorp/otto/blob/master/command/dev.go#L78) in order to find out how to destroy my sample machine.

Coming from vagrant and
```
$ vagrant help status
Usage: vagrant status [name]
    -h, --help                       Print this help
```
I was expecting
```
$ otto help dev
```
to give me something.
I mean, 
```
$ otto dev help
````
is fine, but not immediately clear.

**Comment by phinze** [comment]
Good call, we'll get this cleaned up.
