### ISSUE TITLE
libsqlite3-dev not installed by default in hashicorp/precise64

### ISSUE THREAD

**Issue by listrophy** [hashicorp/otto#76]
I tried spinning up an otto dev environment. I got to the point of running `otto dev ssh` then `bundle`. Bundle failed because `libsqlite3-dev` was not installed (I'm using `hashicorp/precise64` for the box).

Running `sudo apt-get install libsqlite3-dev` then `bundle` fixed the issue. I'd provide a PR, but I don't really know where to start. :smile:

**Comment by adambarthelson** [comment]
Take a look at the [dependencies](https://ottoproject.io/intro/getting-started/deps.html) section of the Getting Started guide.

**Comment by listrophy** [comment]
OK. I just read that section, but I don't see how that helps.

Basically, I just need a `sudo apt-get install libsqlite3-dev` during the provisioning process.

**Comment by phinze** [comment]
@listrophy hi! :wave: 

Otto's development environment should have common necessary packages available by default, and I think `libsqlite3-dev` qualifies. Adding it now! :+1:

**Comment by listrophy** [comment]
Thanks @phinze! :heart:
