### ISSUE TITLE
mongodb dependancy fails in Getting Started guide

### ISSUE THREAD

**Issue by noderat** [hashicorp/otto#91]
Following the Getting Started guide under dependencies the mongodb example failes, issuing an error about a missing `.ottoid` file.

```
Error compiling Appfile: Dependency 'git::https://github.com/hashicorp/otto.git//examples/mongodb/' doesn't have an Otto ID yet!

An Otto ID is generated on the first compilation of the Appfile.
It is a globally unique ID that is used to track the application
across multiple deploys. It is required for the application to be
used as a dependency. To fix this, check out that application and
compile the Appfile with `otto compile` once. Make sure you commit
the .ottoid file into version control, and then try this command
again.
```

The file is present in the repository, however inspecting `.otto/appfile/deps/{uuid}/` only Appfile is not cloned from the repository, `.ottoid` is missing.

Also the git url has a double forward slash in the URI.

**Comment by bascht** [comment]
Looks like a dup of #81, no?

**Comment by piotrj** [comment]
Yep, it's a duplicate. But this one has way better description ;)

**Comment by mitchellh** [comment]
Dup of #81. We know what is causing this and will fix it very soon.
