### ISSUE TITLE
Installation documentation a little vague

### ISSUE THREAD

**Issue by mikefrancis** [hashicorp/otto#94]
Hi,

Having a play with Otto now and there seems to be a bit of a gap in the installation where you move the file to `/usr/bin` on Mac.

Just thinking this might be a barrier to entry for some beginners.

Great work on Otto though, love using it.

**Comment by mitchellh** [comment]
The installation instructions have this: "The final step is to make sure that `otto` is available on the PATH." and then link to how to set this up. This is equivalent to this.

I think we should be covered.

**Comment by mitchellh** [comment]
Also thanks for trying it out :)

**Comment by mikefrancis** [comment]
@mitchellh Ok, I did see that but just wanted to voice that I only knew what to do as I've had do this before.

To a complete beginner I think this StackOverflow link would be quite confusing as it doesn't mention Otto and assumes quite a high level of knowledge.

I think if you just explained this in the docs (or even just a summary) you would avoid the barrage of questions when Otto starts to gain traction. It also might curb the drop out rate - I know in the past if I've hit a road block in a particularly challenging install process, that's where my interest in the project has ended :smile:

**Comment by roikles** [comment]
I found this really confusing too. If the readme said something along the lines of 'Download the binary and move it to an appropriate location e.g. /usr/bin/, then add that location to your PATH' it would really simplify the instructions.

**Comment by tomhoad** [comment]
+1
