### ISSUE TITLE
git dependency example on site is a bit misleading

### ISSUE THREAD

**Issue by mootpt** [hashicorp/otto#98]
reviewing: https://ottoproject.io/docs/appfile/dep-sources.html
```
dependency {
    source = "github.com/hashicorp/otto/examples/mongodb"
}
```

Is a bit misleading, as you need to specify the branch in this case.

It seems Otto does not automatically recognize GitHub URLs when multiple branches exist. This maybe a misunderstanding on my part.

**Comment by mitchellh** [comment]
This should work. What error are you getting? 

The URL itself isn't valid in a browser, but this is the format that we use in Otto to identify sub-directories in GitHub. For branches, you have to use the `?ref` parameter. See https://ottoproject.io/docs/appfile/dep-sources.html
