### ISSUE TITLE
Node is not pre-installed

### ISSUE THREAD

**Issue by mindmelting** [hashicorp/otto#99]
Ran:

```
otto compile
otto dev
otto dev ssh
node server.js
```

Received:

```
vagrant@precise64:/vagrant$ node server.js
The program 'node' can be found in the following packages:
 * node
 * nodejs
```

The logs seem to indicate that Node was installed, but it was not available when ssh'ing into the box.

Installed through a brew cask and is v0.1.0

**Comment by jrnt30** [comment]
I too had this issue as well.  I compiled the binary from source from v0.1.1 and it is working. The issue you are seeing is that the "{{ node_version }}" is not being properly parameterized into the Vagrantfile. 

If you need to build form source it's relatively self contained, as they have a Vagrantfile as well, however you may need to change the base box name from "chef/" to "bento/" per #101

**Comment by jrnt30** [comment]
@mindmelting As a followup, it appears the cask has been upgraded to v0.1.1 so you may be able to simply upgrade your package and run the provisioner again for the Vagrant box

**Comment by phinze** [comment]
Hey folks, sorry for the trouble here - this should have been fixed in v0.1.1 - if it's still happening on that version let me know and we can reopen.

**Comment by mindmelting** [comment]
Yep worked fine, thanks :)

**Comment by lfilho** [comment]
Using otto 0.1.2 and this happened to me. Any clues?
